### ISSUE TITLE
JS issues on IE8

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#108]
WAMP-over-Longpoll works with IE9, but not IE8 - needs general JS fiddling for this crapware.

Also: old Android WebKit needs testing / possibly fiddling as well.

**Comment by norn** [comment]
+1

**Comment by oberstet** [comment]
Closing this one: we don't even have a device/test setup around anymore.

In retrospect, I'd say, our dependency polyfill for typed array did not support the mentioned browser/OS versions.
