### ISSUE TITLE
Protocol violations use illegal WebSocket close code

### ISSUE THREAD

**Issue by gajanak** [crossbario/autobahn-js#141]
It seems autobahn uses on any protocol error code 1002 to close the websocket.

```
self._protocol_violation = function (reason) {
     log.debug("failing transport due to protocol violation: " + reason);
      self._socket.close(1002, "protocol violation: " + reason);
   };
```

In Current browsers (firefox,chrome) this produces errors.

```
 Uncaught InvalidAccessError: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1002 is neither.18.Factory.create.transport.close @ autobahn.js:4482
 InvalidAccessError: A parameter or an operation is not supported by the underlying object
```

The w3c specification says (http://www.w3.org/TR/websockets):

```
The close() method must run the following steps:
 If the method's first argument is present but is not an integer equal to 1000 or in the range 3000 to 4999, throw an InvalidAccessError exception and abort these steps.
```

Perhaps Autobahn should use a different error code. 1002 seems to be reserved for websocket internal protocol errors.

**Comment by oberstet** [comment]
The WAMP spec should define a proper error code (from 3000-4999 range) for transport level serialization and other low-level errors.

**Comment by chinalwb** [comment]
Same issue to me:

>>>
Uncaught DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1002 is neither.
    at Object.transport.close (http://10.11.8.201:8080/build/app.js:7069:23)
    at Session.self._protocol_violation (http://10.11.8.201:8080/build/app.js:5375:20)
    at Object.Session.self._socket.onmessage (http://10.11.8.201:8080/build/app.js:6079:24)
    at WebSocket.websocket.onmessage

**Comment by oberstet** [comment]
this has been fixed:

```
oberstet@intel-nuci7:~/scm/crossbario/autobahn-js$ find lib -type f -exec grep -Hi "self._socket.close" {} \; 
lib/session.js:      self._socket.close(3002, "protocol violation: " + reason);
lib/session.js:                      self._socket.close(3000);
lib/session.js:               self._socket.close(3000);
```
