### ISSUE TITLE
CDN code contains duplicates copyright notices

### ISSUE THREAD

**Issue by sametmax** [crossbario/autobahn-js#143]
https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz

**Comment by oberstet** [comment]
Ah, ok. That's weird. The library is minimized using the Google Closure compiler (https://github.com/tavendo/AutobahnJS/blob/master/SConstruct#L49). I have no clue how it extracts copyright notices ..

**Comment by oberstet** [comment]
won't fix
