### ISSUE TITLE
Currently fails to connect when run in a Web Worker

### ISSUE THREAD

**Issue by a-musing-moose** [crossbario/autobahn-js#146]
It is not currently possible to run an autobahn connection within a Web Worker. 

When using a web worker that looks something like this:

```
importScripts('http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz');
var wsuri = (self.location.protocol === "http:" ? "ws:" : "wss:") + "//" +
            self.location.host + "/ws";


// the WAMP connection to the Router
//
var connection = new autobahn.Connection({
    url: wsuri,
    realm: "realm1"
});

connection.onopen = function (session, details) {
    console.log("Connected");
}

connection.onclose = function (reason, details) {
    console.log("Connection lost: " + reason);
}

connection.open();
```

onclose gets called with reason = "unsupported".

I did eventually manage to get it working with a combinations of a slightly nasty hack and a tiny patch to the autobahn.js file.

e.g. before calling `importScripts` I added a line: 

```
var window = self;
```

This allowed me to connect and even register functions etc. I did hit an additional issue when using `then` after the register function. e.g.:

```
    session.register('example.eacho', function(value) {
        return value;
    }).then(
        function (reg) {
            postMessage('registered procedure');
        },
        function (err) {
            postMessage('failed to register procedure');
        }
    );
```

This cause a JS error about calling `postMessage` with the incorrect parameters. This I presume is because when within a webworker `self.postMessage` is different `window.postMesssage` in the browser itself. And I had just mapped `var window = self;`. 

I also managed to get around this by making a minor patch to autobahn.js. Around line 9 in the compiled file is:

```
var canPost = typeof window !== 'undefined'
    && window.postMessage && window.addEventListener
    ;
```

I modified it to:

```
var canPost = typeof window !== 'undefined'
    && window.postMessage && window.addEventListener
    && typeof self === "undefined";
```

And now it all appears to work as expected, which is pretty neat.

I have no idea if these are issue with autobahn itself or one of it's dependencies but I'll do some digging.

**Comment by goeddea** [comment]
What browser are you using for this? Issues here should have been fixed (see #133).

**Comment by a-musing-moose** [comment]
Hey @goeddea I am using Chrome Version 43.0.2357.132 (64-bit) on Linux (Ubuntu 14.04).

**Comment by goeddea** [comment]
Will look into this, but will only have time to do so next week. Do you have any test could I could start with?

**Comment by oberstet** [comment]
ABJS can be run in webworkers, pls see:

* https://crossbario.com/blog/Websocket-Persistent-Connections/
* https://crossbario.com/blog/Free-Your-Code-Backends-in-the-Browser/
