### ISSUE TITLE
add returning promise in procedure to documentation

### ISSUE THREAD

**Issue by goeddea** [crossbario/autobahn-js#172]
see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/autobahnws/tSeP3zuF6hY/3BSjiC95CwAJ (also: see https://github.com/crossbario/crossbardocs/issues/50

**Comment by ericchapman** [comment]
solution

    var when = require('when');

    method() {

        var d = when.defer();

        session.call("com.example").then(
            function(result) {
                d.resolve(result);
            }
        );

        return d.promise;
    }

**Comment by oberstet** [comment]
Oh, `session.call` _already_ returns a promise, if that is what you need. Above code is equivalent to

```javascript
method() {
   // session.call() already returns a whenjs promise
   return session.call("com.example");
}
```

The example I had in mind is more for transforming a callback into a promise, like what is needed when doing an HTTP request from JavaScript (eg https://github.com/crossbario/autobahn-js/blob/master/package/lib/util.js#L55).

```javascript
var http_post = function (url, data, timeout) {
   var d = when.defer();

   var req = new XMLHttpRequest()

   // the callback that we want to convert into a promise
   req.onreadystatechange = function () {
      if (req.status === 200) {
         d.resolve(req.responseText);
      else {
         d.reject(req.status);
      }
   }

   // whenjs has the actual user promise in an attribute
   return d.promise;
}
```

> AutobahnJS comes with whenjs as underlying deferred library per default, but allows to configure a different library also (`use_es6_promises` and `use_deferred`) : http://autobahn.ws/js/reference.html#connection-options. At run-time, the auto-configured whenjs, or the explicitly selected deferred constructor is accesible at  http://autobahn.ws/js/reference.html#Connection.defer

**Comment by ericchapman** [comment]
@oberstet Sorry Tobias.  I simplified the code in the above example.  The "session.call" was buried in the async code so I could not just return the promise from the "session.call".  It was purely for example purposes.  But the promise was what I was looking for.

**Comment by ericchapman** [comment]
@oberstet Hey Tobias.  We are the ones who posted this article 

https://medium.com/@theHQ/using-mock-and-trial-to-create-unit-tests-for-crossbar-applications-867e5b941cf2#.rvicqdzhj 

I am going to do another one for JS if it is helpful.

**Comment by goeddea** [comment]
@ericchapman - More education about WAMP & Crossbar.io is always welcome! (And thanks for your Python post.)

**Comment by ericchapman** [comment]
@goeddea Will do Alexander :)

**Comment by oberstet** [comment]
@ericchapman I filed https://github.com/crossbario/crossbardocs/issues/60 as a follow up
