### ISSUE TITLE
FYI: Issue with Angular 2 (Beta0) and AutobahnJS v0.9.9

### ISSUE THREAD

**Issue by bradws** [crossbario/autobahn-js#175]
Hi guys,

Just as an FYI: I seem to have an issue getting AutobahnJS and Angular 2 working together. I have raised an [issue](https://github.com/angular/angular/issues/6447) at the Angular github page as I don't *think* its a problem with AutobahnJS.

My end goal is to get an Angular2 Service working with AutobahnJS (but just at the baby steps at the moment).
Anyway, once I've got all that sorted out, I would be happy to provide a working example.

Cheers,
bradws.

**Comment by creat-or** [comment]
@bradws any success by now? I ended up loading the file via cdn as a temporary solution, but yeah... ^^

**Comment by bradws** [comment]
No I spent a lot of time on this and I couldn't get it working. (days!). I think it has something to do with the async nature of AutobahnJS - essentially I needed access to the 'session' object from the session variable:
```
connection.onopen = function (session) {

**Comment by bradws** [comment]
No I spent a lot of time on this and I couldn't get it working. (days!). I
think it has something to do with the async nature of AutobahnJS -
essentially I tried to get access to the 'session' object from the session
variable:

export class myMessageService {
    constructor() {
        van connection = new autobahn.Connection( {url: '...', realm: '...' } );
        connection.onopen = function (session) {
            // ...
        }
    }
    DoFunct1();    // This function returns a value
}

Inside the constructor, I can pub/sub and reg/call no problems. But I need
the session variable *outside *this function so I could put it into root
methods in a class so one can eventually do something like:

var x = myMessageService.DoFunct1( someParameter );

I'm wanting something like AngularWamp
<https://github.com/voryx/angular-wamp> but for Angular2. AngularWamp works
great as it has clear separation of concerns. The author is NOT porting it
to Angular2 so I decided to give it a go myself. In theory, it sounds
simple enough.

I tried things like:

export class myMessageService {
    var mySession: autobahn.Session;
    constructor() {
        van connection = new autobahn.Connection( {url: '...', realm: '...' } );
        connection.onopen = function (session) {
            this.mySession = session;
            // ...
        }
    }
    DoFunct1(
        this.mySession.call( ...)      // this.mySession is undefined
    );
}

but no luck. Plus I'm a bit new to Angular2, etc.

**Comment by bradws** [comment]
I'm still trying though. Any ideas ?

**Comment by davidwdan** [comment]
@bradws We're not porting it to Angular 2 because Angular 2 is structured very differently, so it'll require a completely new version.  The current version uses a lot of promises.  The new version will be RxJS based with Observables.  Either way, you should be able to use Autobahn in it's current form, without too much trouble.  When I get some free time, I'll work up an example.

**Comment by Creator** [comment]
@bradws Thanks for mentioning me, guys. :smile:

**Comment by oberstet** [comment]
@davidwdan Thanks for explaining!

We probably should put up a dedicated docs page: "How to use AutobahnJS from popular UI frameworks"

I know people are using it in production with:

* Polymer
* Knockout
* Angular 1

Our own stuff is done using Knockout.

There also is https://github.com/paulpdaniels/rx.wamp

**Comment by bradws** [comment]
Hi guys,
I wasn't able to get it working with Angular 2 ( <= RC4 ), so i ended up using [Wampy](https://github.com/KSDaemon/wampy.js/)

**Comment by davidwdan** [comment]
@bradws we've been using autobahn with Angular 2 (currently RC3), with TypeScript for a while now.  Here are the instructions that we use to get it working:

```typings install autobahn --ambient --save```
```typings install when --ambient --save```

```npm install bufferutil utf-8-validate --save```  When https://github.com/crossbario/autobahn-js/issues/196 is resolved, this won't be needed.
```npm install autobahn --save```

and then you can import the components you need from autobhan:

```import {Connection, Session, IConnectionOptions} from "autobahn";```

**Comment by michaeljpeake** [comment]
Here's hoping for a good RxJS WAMP module written in TypeScript so everything plays nicely with Angular 2. The suggestion from @davidwdan works for now though.

**Comment by codegastudio** [comment]
Could you give an exemple now that Angular 2 has an official release plz ?

**Comment by darkl** [comment]
@michaeljpeake I had written type declarations for rx.wamp, see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/rx.wamp).

**Comment by KMax** [comment]
Did anyone manage to include AutobahnJS in a Angular 2 project?

I installed the module and the [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/autobahn):
```
npm install autobahn --save
npm install @types/autobahn
```
but anyway the browser tries to load by a URL:
```
GET XHR http://localhost:3000/autobahn [HTTP/1.1 404 Not Found 1ms]
```

though the Typescript compiler do compile the code:
```
import {Connection, Session} from 'autobahn;

@Injectable()
export class WAMPService {
  connect(): void {
    let connection = new Connection({
      url: 'ws://localhost:8080/ws',
      realm: 'realm1'
    });
}
```

**Comment by BlueBeN82** [comment]
@KMax Did you solve your problem meanwhile? I have the same problem right now...

**Comment by KMax** [comment]
@BlueBeN82 I switched to [Angular CLI](https://cli.angular.io) which is based on webpack. I added link to the CDN version of autobahnjs in index.html and put `declare var autobahn: any;` in .ts file where autobahnks is used.

**Comment by cmarsh599** [comment]
could https://www.npmjs.com/package/angular2-websocket-service be used ?

**Comment by datasmithtech** [comment]
Has anyone looked at using https://www.npmjs.com/package/angular2-websocket-service ?
