### ISSUE TITLE
Feature Request: return a promise in onchallenge

### ISSUE THREAD

**Issue by konsultaner** [crossbario/autobahn-js#178]
I would like to have the chance to return a promise for the signature creation in the onchallenge handler. Some [two factor](https://github.com/wamp-proto/wamp-proto/issues/183) authentications like oAuth2 have a async signature or token creation. I currently try to connect WAMP to oAuth2.

something like that:

``` javascript
return function (session, method, extra) {
    if (method === "wampcra") {
        return autobahn.auth_cra.sign(autobahn.auth_cra.derive_key(password || "", extra.salt,extra.iterations,extra.keylen), extra.challenge);
    } else if (method === "oauth2.authorization_code_grant") {
        return new Promise(...);
    }
}
```

**Comment by oberstet** [comment]
Yes, agreed. That would be useful!

**Comment by konsultaner** [comment]
@oberstet according to 

https://github.com/cujojs/when/issues/505#issuecomment-374581157

and

https://github.com/crossbario/autobahn-js/blob/8ad8f0ece7112d9dca82f80240b28042b578474f/lib/session.js#L930

this issue is solved?

**Comment by oberstet** [comment]
yep, solved
