### ISSUE TITLE
Include browser version in npm package

### ISSUE THREAD

**Issue by SnareChops** [crossbario/autobahn-js#180]
Recently we had a discussion and made a move to remove our dependency on bower for our application. This has greatly improved consistency, and lowered our dependency count. However the npm version of Autobahn does not include a browser compatible version.

I see that a standalone version in being created in the `Makefile`

```
browserify lib/autobahn.js --standalone autobahn -o build/autobahn.js
```

However this is being ignored in the npm package in the `.npmignore`.

Would it be possible to include this file in the npm package?

**Comment by oberstet** [comment]
>  the npm version of Autobahn does not include a browser compatible version

The npm version is for running under node, and we use Browserify to _build_ a browser compatible package from that.

The npm package does not include built artifacts - neither node nor browser specific ones. The latter are also published here https://github.com/crossbario/autobahn-js-built

**Comment by yatskevich** [comment]
@SnareChops If you are still interested, I've created a fork of [autobahn-js-built](https://github.com/crossbario/autobahn-js-built) and added a [package.json](https://github.com/yatskevich/autobahn-js-built/blob/master/package.json) to it so one can include `autobahn` in `package.json` as a dependency:
```
"dependencies": {
  "autobahn": "yatskevich/autobahn-js-built",
  ...
}
```

This is a very dirty solution, but it works.

@oberstet would do you think about including `package.json` along with `bower.json` in `autobahn-js-built`?

**Comment by oberstet** [comment]
I agree, we probably should include both of these files. If that works npm and it doesn't harm.

**Comment by yatskevich** [comment]
npm fetches autobahn from autobahn-js-built without any issue. The only warning I see is emitted by webpack (I use webpack in my app): 

```
WARNING in ./~/autobahn/autobahn.js
Critical dependencies:
1:481-488 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/autobahn/autobahn.js 1:481-488
```

**Comment by oberstet** [comment]
This is now published, please see here https://github.com/crossbario/autobahn-js-built/tree/v0.10.0
