### ISSUE TITLE
v0.9.9  session.js:495 = TypeError: Cannot read property 'topic' of undefined

### ISSUE THREAD

**Issue by fredli74** [crossbario/autobahn-js#183]
subs[0] is undefined if an event is fired and you have already unsubscribed from the last channel. 

Should probably be a  `(subs[0] && subs[0].topic)`

**Comment by polyclick** [comment]
+1

**Comment by erichonkanen** [comment]
Hello, I am also getting this and wasn't sure what the issue was but just found this, is this a bug?

**Comment by oberstet** [comment]
Fixed in above PR

**Comment by jiminssy** [comment]
I was seeing this issue in version 0.10.x. So I got the version 0.11.1 which has the fix (subs[0] && subs[0].topic) in it. At first it seemed like the problem went away. But when started hammer testing to repeat the steps
- connect - connected
- subscribe - subscribed
- disconnect - disconnected
in those following chains repeatedly much faster than before from the UI (which users can potentially do) occasionally I still get this issue.

**Comment by goeddea** [comment]
Do you have test code to replicate this problem that you could link to?
