### ISSUE TITLE
Adding HTTP headers for WebSocket (and Longpoll) transports

### ISSUE THREAD

**Issue by aalmazan** [crossbario/autobahn-js#184]
Is there currently a way to do this in autobahn-js? I know that there is a way to do this in the Python version (i.e .http://stackoverflow.com/questions/16187872/how-to-add-basic-auth-header-in-autobahn-client-tool), but there's no mention of this in the js documentation or code.

**Comment by rafaellive** [comment]
I have the same question! Anyone found a solution?

**Comment by aalmazan** [comment]
@rafaellive For my purposes, what I did instead was add a few modifications on crossbar and autobahn-python and passed in some extra query params on my frontend code. Hope that helps!

**Comment by dustinlacewell** [comment]
+1 for the ability to set the http headers on JS websocket connections.

**Comment by oberstet** [comment]
Yeah, we could add custom HTTP header for WebSocket and Longpoll transports, but not for RawSocket transport (as that isn't based on HTTP).

**Comment by matthewh** [comment]
Specifically for Basic Authentication from a browser, structure your url as "ws://username:password@myhostname.com/" and the correct headers will be generated.

AFAIK It is not possible to add custom header, like "X-My-Favorite-Color: Blue", when establishing a web socket connection from a web browser.

Custom HTTP headers would only be an option for implementations using Node and the ws library.

**Comment by tonix-tuft** [comment]
What is the current state of this feature? Will it be possible to add custom HTTP headers to Autobahn WebSocket connections?

**Comment by matthewh** [comment]
The short answer is [no](https://stackoverflow.com/a/4361358), there is no method in the JavaScript WebSockets API for specifying additional headers for the client/browser to send.

**Comment by tonix-tuft** [comment]
Is there at least a way, using autobahn.js, to specify a custom value for the `Sec-WebSocket-Protocol` header? When we use the `WebSocket` constructor, we can do the following:

```
var ws = new WebSocket("ws://example.com/path", "protocol");
```

Can we pass the second option (`"protocol"`) to the `autobahn.Connection` constructor somehow?

**Comment by tonix-tuft** [comment]
Autobahn JS passes the following header by default:

```
Sec-WebSocket-Protocol: wamp.2.json, wamp.2.msgpack
```

I'd like to have the possibility to append another custom value to it, e.g. `my.protocol`:

```
Sec-WebSocket-Protocol: wamp.2.json, wamp.2.msgpack, my.protocol
```

Is it possible?

**Comment by tonix-tuft** [comment]
The only "hacky" way I found out was to force the `protocols` parameter in `options` to:

```
new autobahn.Connection({
        url: 'ws://localhost/ws',
        realm: 'realm1',
        protocols: ['wamp.2.json', 'wamp.2.msgpack', 'my-custom-protocol']
})
```

This way I can send `my-custom-protocol`, though I am using an undocumented options' parameter (`protocols`). Could it be reliable?

**Comment by matthewh** [comment]
@tonix-tuft We also set the protocols manually in some cases to ensure compatibility when passing messages between clients. Some WAMP clients don't do well when going from a client that sends messages in MSGPACK to a client that only supports JSON. Could it be an oversight that the `protocols` attribute of `autobahn.Connection` is undocumented? I thought that it was the recommended way of forcing a specific protocol (or to supply alternatives as you suggest).

**Comment by tonix-tuft** [comment]
```
Could it be an oversight that the protocols attribute of autobahn.Connection is undocumented? 
```

@matthewh I don't know, but setting this parameter manually seems to work pretty well for my use case, and as I understood, for yours.

Thank you for sharing your thoughts!

**Comment by oberstet** [comment]
the websocket subprotocol names that WAMP uses are strictly defined (and derive of the serializer in use):

* https://github.com/crossbario/autobahn-js/blob/c380038a7e7637963299633eae0e7e1abe124fe3/packages/autobahn/lib/transport/websocket.js#L37

you can manually override subprotos announced via Transport.protocols:

* https://github.com/crossbario/autobahn-js/blob/c380038a7e7637963299633eae0e7e1abe124fe3/packages/autobahn/lib/connection.js#L154
