### ISSUE TITLE
Remove `ws` from browser builds

### ISSUE THREAD

**Issue by davidwdan** [crossbario/autobahn-js#196]
Currently, when installing autobahn with npm for use in the browser (ie. angular2), you need to manually install `bufferutil` and `utf-8-validate` to fulfill unmet dependencies by `ws`.  Is there any reason why we can't remove `ws` from browser builds?  I'm assuming it is only used in nodejs.

``` js
  "browser": {
    "lib/transport/rawsocket.js": false,
    "ws": false
   ....
```

**Comment by oberstet** [comment]
`ws` is not needed in browsers, yes. The browser version is built using browserify. Any idea how we make it skip the unneeded parts?

**Comment by davidwdan** [comment]
In my testing, adding `"ws": false` to the `bowser` section of `package.json`, worked.

**Comment by oberstet** [comment]
Ok, so we would add that to https://github.com/crossbario/autobahn-js/blob/master/package/package.json#L6

**Comment by blazzy** [comment]
Could a pre-built browser version be published to npm?

That would allow folks to install from npm and use whatever build system they please without having to solve issues like this all over again.

**Comment by oberstet** [comment]
Ok, I've managed to cut down browser version to 1/3 of original size (from 181KB to 58KB for the jgz):

```console
(cpy2712_1) oberstet@office-corei7:~/scm/crossbario/autobahn-js$ ls -la build/
insgesamt 896
drwxrwxr-x 2 oberstet oberstet   4096 Nov 15 11:14 .
drwxrwxr-x 7 oberstet oberstet   4096 Nov 15 11:14 ..
-rw-rw-r-- 1 oberstet oberstet 573208 Nov 15 11:14 autobahn.js
-rw-rw-r-- 1 oberstet oberstet  58009 Nov 15 11:14 autobahn.min.jgz
-rw-rw-r-- 1 oberstet oberstet 198906 Nov 15 11:14 autobahn.min.js
-rw-rw-r-- 1 oberstet oberstet    168 Nov 15 11:14 CHECKSUM.MD5
-rw-rw-r-- 1 oberstet oberstet    195 Nov 15 11:14 CHECKSUM.SHA1
-rw-rw-r-- 1 oberstet oberstet    273 Nov 15 11:14 CHECKSUM.SHA256
-rw-rw-r-- 1 oberstet oberstet   1086 Nov 15 11:12 LICENSE
```
