### ISSUE TITLE
Issue with websocket.binaryType

### ISSUE THREAD

**Issue by deli6z** [crossbario/autobahn-js#200]
On Chrome 48.0.2564.116 (64-bit) getting a console error 'The provided value 'arrayBuffer' is not a valid enum value of type BinaryType'. 
simply changing 'arrayBuffer' to 'arraybuffer' fixes it, like this:
websocket.binaryType = 'arraybuffer';
Please help

**Comment by oberstet** [comment]
See https://github.com/crossbario/autobahn-js/commit/b9ab5d80964fedb7077fcee9926ffbb461e273ae#commitcomment-17497022
