### ISSUE TITLE
Upon reconnecting after connection "lost", the connection.onopen is NOT triggered...

### ISSUE THREAD

**Issue by erichonkanen** [crossbario/autobahn-js#201]
Hello,

I am having an issue trying to figure out how to determine when a connection has been reestablished and thus triggering some code. It seems like when a connection drops, it does indeed reconnect (verified via aws logs), however the `connection.onopen` is not triggered and so I have no way of knowing in the client that it was reconnected...

Here is my code (coffeescript):
```
initiate: (caller, openCallback, closeCallback)->
    ###
    Initiates and opens a wamp connection with the chatHost and
    calls handlers for connection.onopen and connection.onclose.

    @public
    @method initiate
    @param caller A context to apply to the callbacks.
    @param openCallback {Function} A callback handler for opening a session.
    @param closeCallback {Function} A callback handler for closing a session.
    @return autobahn.Connection
    ###
    # Get a wamp connection from autobahn.
    connection = @getConnection()

    # Set the context of the callbacks - this allows accessing 
    # methods and variables from the original context which might
    # be a component etc.
    _openCallback = ->
      openCallback.call caller ? this, arguments
    _closeCallback = ->
      closeCallback.call caller ? this, arguments

    # Handle actions that take place upon opening a session.
    connection.onopen = (session, details)=>
      log.info "Autobahn connection opened."
      # Store the session for later use.
      @set 'session', session
      _openCallback?(session, details)

    # Handle actions that take place upon closing a session.
    connection.onclose = (reason, details)=>
      log.info "Connection was closed with reason: #{reason}."
      _closeCallback?(reason, details)
      return true  # enable the autobahn reconnect.

    # Check if the connection is open and if so subscribe the session
    # otherwise fire the open callback if it was supplied.
    if not connection.isOpen
      connection.open()
    else
      _openCallback?()

    return connection
```
Is the expected behavior that `connection.onopen` should fire when the connection is reestablished? If not, how can I be notified it was reestablished?

**Comment by erichonkanen** [comment]
ps - the only way around this right now is if I manually reconnect like such:
```
    # Handle actions that take place upon closing a session.
    connection.onclose = (reason, details)=>
      log.info "Connection was closed with reason: #{reason}."
      _closeCallback?(reason, details)
      @initiate caller, _openCallback, _closeCallback
      return false  # disable the autobahn reconnect.
```
this works however I get an error saying something like "connection is already closing or closed" in the javascript console

**Comment by erichonkanen** [comment]
I think this line is backwards:
```
"lost": The connection had been formerly established at least once, but now was lost. Automatic reconnection will happen unless you return falsy from this callback.
```
If you return `false` from L370, then this line will evaluate to true and it will try to reconnect
https://github.com/crossbario/autobahn-js/blob/master/package/lib/connection.js#L387

**Comment by meejah** [comment]
Yeah, those definitely look like a contradiction ... I guess the "least disruptive" change would be to fix the documentation...?
(/cc @oberstet)

**Comment by erichonkanen** [comment]
I just verified it is indeed the case, the documentation should state `unless you return truthy`

**Comment by meejah** [comment]
Great, thanks for tracking this down @erichonkanen !

**Comment by erichonkanen** [comment]
on a separate note when it reconnects I get an autobahn warning but not sure what it's from:
![image](https://cloud.githubusercontent.com/assets/230757/15307052/6910c87c-1b84-11e6-9cc9-eb9be1524c0b.png)

**Comment by oberstet** [comment]
@erichonkanen The docs correction has been merged, and the other one rgd `arrayBuffer` is here https://github.com/crossbario/autobahn-js/issues/200. So we can close this issue?

**Comment by erichonkanen** [comment]
sounds good thanks!
