### ISSUE TITLE
add support for WAMP cryptobox

### ISSUE THREAD

**Issue by konsultaner** [crossbario/autobahn-js#203]
Crossbar has end-to-end encryption + transparent payload. Is there a plan to implement it with autobahn|js? This might depend on #189?

By the way there is a [asm.js based library for NaCl](https://github.com/tonyg/js-nacl) compiled from the original NaCl lib.

**Comment by oberstet** [comment]
Yes, we will have it.

> This doesn't (strictly) depend on #189, as we can use MessagePack serialization.

**Comment by oberstet** [comment]
@konsultaner The library you link above: the idea of using the "real thing" is definitely interesting! Tradeoff might be the size, but yeah, we should consider that. A built step here could clone above repo, clone the libsodium repo, and build the JS for bundling. Or we just reuse the upstream ready made JS library.

**Comment by oberstet** [comment]
Actually, the issue here is independent from #189, as long as one uses CBOR, MessagePack or UBJSON as the outer serializer, since these can transport the "transparent payload" thing, which is binary.

**Comment by oberstet** [comment]
fwiw, this (in a way) will come via XBR support (which is also using payload transparency and end-to-end encryption - though slightly different / expanded)

related issues:

* https://github.com/crossbario/autobahn-js/issues/410
* https://github.com/crossbario/autobahn-js/issues/411

**Comment by oberstet** [comment]
ok, so ABJS now supports XBR - which is using similar end-to-end encryption as WAMP-cryptobox. however, we won't support (for now) raw WAMP-cryptobox e2e for non-XBR WAMP - as ABPy does
