### ISSUE TITLE
Does onopen officially return "details"?

### ISSUE THREAD

**Issue by eddieajau** [crossbario/autobahn-js#213]
In the documentation, the `onopen` event takes only one argument `session` (see http://autobahn.ws/js/reference.html#connection-callbacks).

However, `onopen` is invoked with a second argument `details`.

``` js
      self._session.onjoin = function (details) {
         if (self.onopen) {
            try {
               self.onopen(self._session, details);
            } catch (e) {
               log.debug("Exception raised from app code while firing Connection.onopen()", e);
            }
         }
      };
```

See https://github.com/crossbario/autobahn-js/blob/master/package/lib/connection.js#L317

Can we rely on using `details` or has it deliberately not been documented for some reason? 

Thanks in advance.

**Comment by oberstet** [comment]
Yes, you can rely on that - it is part of the public API. This is a doc bug (needs documentation).
