### ISSUE TITLE
Adding TLS to an app

### ISSUE THREAD

**Issue by sscirrus** [crossbario/autobahn-js#218]
I am desperately trying to add TLS to an app that involves 1) a browser running Autobahn|JS as a caller/subscriber and 2) a remote device running Autobahn|Python as a listener/publisher.

Unfortunately, the reference for Autobahn|JS contains nothing more than a sentence on TLS (change 'ws' to 'wss'). I've tried this and it fails to connect.

How can I get better information on implementing TLS with 'wss'? At least, I assume I need a security certificate somewhere, no?

**Comment by goeddea** [comment]
Take a look at http://crossbar.io/docs/Secure-WebSocket-and-HTTPS/ 

If this does not provide you with enough information, then please post further questions to the mailing list - https://groups.google.com/forum/#!forum/autobahn or  https://groups.google.com/forum/#!forum/crossbario.

Closing this for now.
