### ISSUE TITLE
Make use of bufferutil optional

### ISSUE THREAD

**Issue by ThomasHornschuh** [crossbario/autobahn-js#220]
Hi,
as already outlined in my comment on Issue #216 
compiling bufferitil can be troublesome, especially on Windows machines.
The authors of bufferutil recommend in their readme that bufferutil should be used only as optional dependency. Maybe you should consider changing autobahn in this way. 

Regards
Thomas

**Comment by oberstet** [comment]
Nope, sorry. I don't care about Windows anymore

**Comment by ThomasHornschuh** [comment]
And I don't care about operating systems anymore, or at least I don't want to.
When thinking cloud, microservices and PaaS to the end, the operating system which hosts a service should be of no relevance. 
One of the key features of node.js is for me that it does quite a good job in hiding platform dependencies. The exception are native modules and node-gyp. The trouble it can make are not specific to Windows. 
My concern  is not my development machine, because I own and control it, my worry is that  build fail on e.g. a PaaS instance where I can't control or change the environment freely.

My understanding is that bufferutil and utf8-validate are used by ws. ws itself can work without and will automatically use it if it is present. At least the documentation of ws states this, I have not tested. Why not making the both native modules optional?

We selected crossbar for a prototype of our new application architecture because you seem to have the right vision behind it. Your comment above is a bit of disappointment for me and looks contradictory to the vision.

One last general remark:  We as developers are not the guys who are in control which platforms the market use.

Thomas

**Comment by oberstet** [comment]
@ThomasHornschuh Ok, thanks for the explanation of your itch! I see.

> Why not making the both native modules optional?

If you can come up with a PR that

* allows to disable native module deps
* but keeps the default `npm install autobahn` installing native deps
* make sure above still works on the platforms I care (Unix)

I am ready to merge!

I just lack the time and motivation rgd Windows. I finally left Windows some time ago - and simply hate the fact that I still get into Windows fallout all the time ..

**Comment by ThomasHornschuh** [comment]
Ok, I will take the challenge :-)
Anyway, your answer already removed the negative feelings I got from your first comment. Thanks for that.

Thomas

**Comment by oberstet** [comment]
@ThomasHornschuh Cool;) And sorry if I sounded harsh first - no offense! Might just be my lack of patience character wise - meh.

**Comment by oberstet** [comment]
This was fixed (see [here](https://github.com/crossbario/autobahn-js/blob/master/package.json#L17))
