### ISSUE TITLE
async/await syntax not works

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/autobahn-js#226]
Hello! hire is two analogous blocks of my code. First one is written with modern async/await construction and the second with classical Promise. Code was builded with babel.

```
    connection.onopen = async function (session, details) {
            console.log("connection.onopen");

            await session.register('ru.kopnik.model.get',  function (args, kwargs) {
                    //....
            });

            console.log("ru.kopnik.model.get registered");   //**NEVER EXECUTED!!!**
    }
```

output:

> connection.onopen

classical Promise style:

```
        connection.onopen = function (session, details) {
            console.log("connection.onopen");

            session.register('ru.kopnik.model.get', function (args, kwargs) {
                     //...
            })
        }
        .then(console.log("ru.kopnik.model.get registered"), console.error);
```
output:

> connection.onopen
> ru.kopnik.model.get registered
> { error: 'wamp.error.procedure_already_exists',
>   args: [ 'register for already registered procedure \'ru.kopnik.model.get\'' ],
>   kwargs: {} }

As far as I can see first code register procedure but handle execution on forever

**Comment by oberstet** [comment]
Interesting.

Could you try setting `use_es6_promises` on the Connection constructor options?

* https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#connection-options
* https://github.com/crossbario/autobahn-js/blob/master/package/lib/connection.js#L31

**Comment by alexey2baranov** [comment]
your code works very nice! we are using it in out project and very funy with WAMP2.0.   

I'm closing this issue. this is our mistake. Sorry)
