### ISSUE TITLE
Missing CURIE prefix throws instead of falling back

### ISSUE THREAD

**Issue by privard** [crossbario/autobahn-js#229]
I was trying to subscribe to topics with colons and realized that autobahn's support of CURIEs was interfering, because it's implementation is a bit naive in my opinion. 

For example, if I call `session.subscribe('com.app.object:1234546.action', onevt)`, autobahn [automatically assumes that I am using a CURIE](https://github.com/crossbario/autobahn-js/blob/master/package/lib/session.js#L1496). So, if the `com.app.object` prefix is not defined it will [throw an error](https://github.com/crossbario/autobahn-js/blob/master/package/lib/session.js#L1502), making it impossible to subscribe to that topic, or any topic containing a colon. 

Wouldn't it make more sense for a topic name having a colon but no prefix matching the CURIE pattern to resolve to the full topic instead of throwing an error? It would then fall onto the subscribe action to return an error if that topic does not exist at the router level. 

What do you think?

**Comment by oberstet** [comment]
I agree that the implementation is "naive" .. reason: best practice for URIs (as we use them) is not having colons.

But what you suggest would work of course: first do CURIE lookup, and when there is no match, assume it is a regular URI and let the router lookup.
