### ISSUE TITLE
Buffered publications tied to invocation return

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/autobahn-js#232]
Hello!

how we can order WAMP messages in strict order. We have many cases when client calls WAMP procedure and this procedure publish message to clients. So the question is how we can ask crossbar to send message after procedure call ended.

**litle example**

``` javascript
client.js
    let veryImportantResult;

    //this topic fired from proc but should handled after proc finished
    await session.subscribe("org.topicAfterProcFinished", function(){
        assert.equal(veryImportantResult!== undefined, true);
        //...
    });

    veryImportantResult= session.call("org.proc");
```

server.js

``` javascript
    session.register("org.proc", ()=>{
        //process.nextTick(   //topic fired on client side before proc complete
        //setTimeout( , 1000)  //indefinite topic order when client call proc many times
        setImmediate(  //works best of all (near 80%)
            function(){
                session.publish("org.topicAfterProcFinished");
            }
        );

        return veryImportantResult
    });
```

After many experiments we could not find good way. The most closer to our needs setImmediate() works 8 from 10 times. So we would like to know what is the best practice to send  WAMP messages in ordered way

**Comment by oberstet** [comment]
Try awaiting acknowledged publications https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#acknowledgement in the body of `org.proc` _without_ the `setImmediate` stuff.

**Comment by alexey2baranov** [comment]
@oberstet 

this was my first test. Without setImeediate(timeout/nextTick) awaited  acknowledged publication handled on client before procedure call finished.

**Comment by oberstet** [comment]
1) `session.publish("org.topicAfterProcFinished", {acknowledge: true});` is wrong. the 2nd arg is event payload. read the docs

2) to take out await/async as a possible source of confusion, try:

```
session.register("org.proc", function () {
    var d = new autobahn.when.defer();
    session.publish("org.topicAfterProcFinished", ['Hello, world!'], {},  {acknowledge: true}).then(function () { d.resolve("event already published previously!"); }, console.log);
    return d.promise;
});
```

Using this, when you call into `org.proc`, you should receive the event first before receiving the result.

Anyway, with acknowledge publication, ordering works (I know).

**Comment by alexey2baranov** [comment]
thank you for your time and sorry for my English) 
> 1) session.publish("org.topicAfterProcFinished", {acknowledge: true}); is wrong. the 2nd arg is event payload
my type. i don't want copy paste full mocha test hire and write short code right into github text field.

> 2) to take out await/async as a possible source of confusion
async/await+babel fast-async plugin works very nice with autobahn. If you want to get event first then this short code is good enough.
`await session.publish("org.topicAfterProcFinished", null, null, {acknowledge: true});`

But we do not need to receive event before proc result. We need receive proc result and then event. This is why we use setImmediate() and other tricks do deffer event sending. In short my question is how to get this order with autobahn: 
1) call proc
2) get proc result
3) get event from proc body

Sorry if my english make you think wrong. Waiting your answer. thanks!

**Comment by oberstet** [comment]
> But we do not need to receive event before proc result. We need receive proc result and then event.

Ahh, ok. Now I at least understand technically what you want to achieve.

This is not possible.

The reason is: publications then would need to be tied to a specific invocation (your procedure being called by the router). Syntactically, it would probably look like:

```
session.register(
    "org.proc",
    function (args, kwargs, details) {
        session.publish(...); // regular immediate publication (not tied to invocation)
        details.invocation.publish(...); // buffered publication that is only actually performed _after_ the invocation returns (successfully)
    }
);
```

Under the hood, the router would need to be able to distinguish between regular publications, and publications tied to an invocation. It would internally buffer the latter until the invocation returns, and only then fire the events.

**I am wondering _why_ you want to have that and what's the use case.**

In any case, this could be done in principle, but it would require WAMP protocol level spec work first .. because the `PUBLISH` WAMP message needs to carry the invocation ID the publication is being tied to etc etc

---

> async/await+babel fast-async plugin works very nice with autobahn. I

Could you describe what that is and how it works? I am interested in that .. we do want to move to the nicer async/await stuff too (and I totally lack time;) ..

**Comment by oberstet** [comment]
This should probably be discussed on the WAMP repo .. it is not a AutobahnJS specific thing.

**Comment by oberstet** [comment]
Another question: do you want the buffered events to be fired only when the invocation returns successfully, or both successfully and on error, or even have the ability to have control over what buffered events should be fired on success and others only for error?

**Comment by alexey2baranov** [comment]
OK. first of all i am vary happy that different languages could not stop our communication)

Now I will try to explain our use case. This feature is very important for our client side ORM. This ORM was inspired by Hibernate and like in Hibernate any model that was loaded from database stores in memory. Now let imagine

1) client {A} create new model (calling remote proc create())
2) server create model and notify every clients about this (server publicates  ".newModelCreated", ID)
3) every clients receive event "newModelCreated" and like to fetch this new model from server (calling remote proc get(ID))
3.1)  client {A} receive the same event and fetch this model too! but this is incorrect because it has this model in memory but create() do not finished yet in this moment. It doesn't receive new model ID yet and can't determine that this new model is the same model as hi creating now.
3.1.correct) client {A} receive "newModelCreated" after create() finished and get this model from memory cache

**Comment by alexey2baranov** [comment]
async/await is syntax sugar. It helps to simple and humanize async code.

Because it is not in spec yet and not supported by any browser you should use babel or any other transpiler to use it. Default babel async/await plugin "transform-async-to-generator" has important limitation. It could not work with methods witch call parent methods (any method with super.someParentMethod()) so we use different plugin called "fast-async".

hope this helps you

**Comment by alexey2baranov** [comment]
> have the ability to have control over what buffered events should be fired on success and others only for error

this would be nice

**Comment by oberstet** [comment]
@alexey2baranov Thanks for explaining your use case! I can follow that, makes sense and is a use case we should IMO address (in WAMP, Autobahn, etc). I'll take this issue over to the WAMP repo/mailing list.

Having more control over what events should be buffered for what invocation outcome would probably look like:

```
// this event is dispatched immediately to subscribers, that is, _before_ the invocation returns
session.publish(...);

// this event is buffered at the router, and only actually dispatched to subscribers
// _after_ the invocation returns (successfully or unsuccessfully)
session.publish(..., {buffered_for: details.invocation_id});

// this event is buffered at the router, and only actually dispatched to subscribers
// _if_ and _after_ the invocation returns _successfully_
session.publish(..., {buffered_for_success: details.invocation_id});

// this event is buffered at the router, and only actually dispatched to subscribers
// _if_ and _after_ the invocation returns _unsuccessfully_
session.publish(..., {buffered_for_error: details.invocation_id});
```

---

Thanks for explaining `fast-async`! I see.

**Comment by alexey2baranov** [comment]
nice! there is another promise design to do this. I don't know what one is best, just write idea you can  think about

```javascript 
details.self.then(()=>session.publish("somy success), (err)=>session.call("some err"));
```

**Comment by oberstet** [comment]
Migrated to https://github.com/wamp-proto/wamp-proto/issues/263
