### ISSUE TITLE
console.error is not a function

### ISSUE THREAD

**Issue by sscirrus** [crossbario/autobahn-js#233]
I'm getting strange errors in autobahn.min.js in Chrome:

```
autobahn.min-ed0fb39….js:240 Uncaught TypeError: console.error is not a function
(anonymous function) @ autobahn.min-ed0fb39….js:240
g @ autobahn.min-ed0fb39….js:239
p @ autobahn.min-ed0fb39….js:240
```

I then ran autobahn.min.js through JSLint and I get 'JSLint was unable to finish' along with lots of errors.

How can we solve the console.error problem? Is there an official patch coming out for this?

**Comment by oberstet** [comment]
cannot reproduce
