### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by kennynaoh** [crossbario/autobahn-js#246]
Hello @oberstet 
I am the member of cdnjs project.
We want to host this library.
And there is a question want to ask.
I found that there is a file on website https://autobahn.s3.amazonaws.com/autobahnjs/0.10.1/autobahn.js is different from the git repo and npm, also the development version https://autobahn.s3.amazonaws.com/autobahnjs/0.10.1/autobahn.js.
Is that the main file you want to host?
Could you please publish the minified and development version to git repo or npm.
Thanks!

https://github.com/cdnjs/cdnjs/issues/7102

**Comment by Jichao** [comment]
@kennynaoh There is minified and developerment version in the git repo https://github.com/cdnjs/cdnjs/issues/7102 according to https://github.com/cdnjs/cdnjs/issues/7102
≈

**Comment by oberstet** [comment]
@kennynaoh Ah, I probably missed to mention: the version of npm is for NodeJS (eg it includes a WebSocket implementation), while the one hosted on S3 is for browsers (and consequently does not include a WebSocket implementation in JS, as the browser has one already in native code).
