### ISSUE TITLE
Bug with session unsubscribe example

### ISSUE THREAD

**Issue by ve3jrw** [crossbario/autobahn-js#248]
Line 9:

      session.unsubscribe(subscription).then(

should be:

      session.unsubscribe(currentSubscription).then(

**Comment by oberstet** [comment]
I think we have many files with "Line 9";)

**Comment by ve3jrw** [comment]
I'm not referring to a file. I'm referring to the online example.  There is only one illustrating pub/sub.
-------- Original message --------From: Tobias Oberstein <notifications@github.com> Date: 11/28/16  3:37 PM  (GMT-05:00) To: crossbario/autobahn-js <autobahn-js@noreply.github.com> Cc: ve3jrw <ve3jrw@gmail.com>, Author <author@noreply.github.com> Subject: Re: [crossbario/autobahn-js] Bug with session unsubscribe example
  (#248) 
I think we have many files with "Line 9";)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crossbario/autobahn-js","title":"crossbario/autobahn-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crossbario/autobahn-js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@oberstet in #248: I think we have many files with \"Line 9\";)"}],"action":{"name":"View Issue","url":"https://github.com/crossbario/autobahn-js/issues/248#issuecomment-263386849"}}}
