### ISSUE TITLE
Allow `onclose` to return a `Promise`

### ISSUE THREAD

**Issue by paulpdaniels** [crossbario/autobahn-js#253]
It would be nice if `onclose` of a `Connection` could support a `Promise` instead of a simple true false. This would allow the user to specify their own custom retry logic instead of relying on `autobahn`.

i.e. (super contrived)

```javascript

connection.onclose = function(reason, details) {
  return new Promise(function(resolve, reject) {
    // ... Show a modal, reconnect?
    // if the user clicks then resolve and attempt a reconnect
    reconnectBtn.addEventListener('click', resolve);
    // Timeout after a period
    setTimeout(reject, 10000);
  });
};
```

My use case is for [rx.wamp](https://github.com/paulpdaniels/rx.wamp) I would like to lift the callback into an `Observable`

So that a user could handle retries fluently:

```javascript
function (e) {
  return e
    // If the observable completes then stop retrying
    .filter(reason => reason === 'closed')

   .mergeScan((retries, error) => 
     Observable.if(
       // Wait until we hit the retry ceiling
       () => retries < 3,
       // When a new value is propagate this will cause a retry, here includes a linear backoff
       Observable.of(retries + 1).delay(100 * retries), 
       // Throw once retry limit is reached
       Observable.throw(error)),
   0);
}
```

The above would be an example of what I hope to be able to lift the retry logic into, but `onclose` will need to accept an async return value in order to facilitate that.

If that would be desirable I can submit a PR to that effect.

**Comment by oberstet** [comment]
No, doesn't fit: Autobahn would nevertheless wait depending on its own retry logic regardless how long any promise returned took. Anyway, I think the AB retry logic is sufficient
