### ISSUE TITLE
Cannot connect to an IPv6 address

### ISSUE THREAD

**Issue by sscirrus** [crossbario/autobahn-js#254]
I've had autobahn working dependably with an IPv4 address (192.168.0.12) but when I try IPv6, it doesn't connect.

    `connection = new autobahn.Connection({
        { 'type': 'websocket', 'url': 'ws://2600:8806:504:600:***:****:****:****:8080' },
    ]`

    'Searching' (never connects).

I also tried enclosing the address in square brackets (with result):

    `connection = new autobahn.Connection({
        { 'type': 'websocket', 'url': 'ws://[2600:8806:504:600:***:****:****:****]:8080' },
    ]

    VM2294:37 WebSocket connection to 'ws://[2600:8806:504:600:***:****:****:****]:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

How can I make this work?

**Comment by oberstet** [comment]
I assume you are using Node, not browser? What's on the server side?

**Comment by sscirrus** [comment]
I'm using Autobahn|JS on the browser and Autobahn|Python 0.9.3-3 on the server side (I'm running on a legacy system that doesn't allow me to update).

**Comment by oberstet** [comment]
Could you try entering the following into the browser address line: `http://2600:8806:504:600:***:****:****:****:8080`.

> Autobahn will render an informational page when a HTTP request comes in that does not contain a upgrade to WebSocket header

By doing so, we can bisect if this is WebSocket specific ..

**Comment by oberstet** [comment]
To be clear: WebSocket is supposed to work with IPv6;) As are browsers and Autobahn. If not, there might be a bug .. and I am interested in tracking this down.

**Comment by oberstet** [comment]
Ah, and even though you cannot upgrade: could you check if this behavior persists for current version (0.17.2)?

**Comment by sscirrus** [comment]
Thanks for your messages - I will get back to you on this.

**Comment by sscirrus** [comment]
Trying IP addresses.

Using my IPv4:
`68.xx.xxx.xx:8080` => 'AutobahnPython 0.9.3-3'

Using my IPv6:
`http://[2600:8806:504:***:****:****:****:****]:8080/` => ERR_ADDRESS_UNREACHABLE
`http://2600:8806:504:***:****:****:****:****:8080` => Chrome redirects to Google search.

**Comment by oberstet** [comment]
I have just tested using Crossbar.io and AutobahnJS: works with IPv6.

Here is what I did:

```
cd /tmp
mkdir test
cd test
crossbar init
```

then modify the transport for (note the `interface` attribute):

```
                    "endpoint": {
                        "type": "tcp",
                        "port": 8080,
                        "interface": "::"
                    },
```

I tested using Chrome and FF on Linux with these addresses:

* http://127.0.0.1:8080/
* http://[::1]:8080/
* http://localhost:8080/
