### ISSUE TITLE
self._init_transport_factories is not a function

### ISSUE THREAD

**Issue by tomkomt** [crossbario/autobahn-js#255]
Executing of "node ." crash on following error:

> TypeError: self._init_transport_factories is not a function
>     at Object.Connection (C:\Users\IBM_ADMIN\Documents\configurator\node_modules\autobahn\lib\connection.js:81:9)
>     at EventEmitter.app.start (C:\Users\IBM_ADMIN\Documents\configurator\server\server.js:56:30)
>     at C:\Users\IBM_ADMIN\Documents\configurator\server\server.js:76:6
>     at C:\Users\IBM_ADMIN\Documents\configurator\node_modules\loopback-boot\lib\executor.js:64:5
>     at C:\Users\IBM_ADMIN\Documents\configurator\node_modules\loopback-boot\node_modules\async\lib\async.js:251:17
>     at C:\Users\IBM_ADMIN\Documents\configurator\node_modules\loopback-boot\node_modules\async\lib\async.js:154:25
>     at C:\Users\IBM_ADMIN\Documents\configurator\node_modules\loopback-boot\node_modules\async\lib\async.js:248:21
>     at C:\Users\IBM_ADMIN\Documents\configurator\node_modules\loopback-boot\node_modules\async\lib\async.js:612:34
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3

**Comment by goeddea** [comment]
We need more information in order to be able to replicate the error. What code are you running (is it one of the examples?), what environment (browser, node.js), what other steps are necessary to produce the bug.

**Comment by tomkomt** [comment]
I know, I'm sorry.

Yes, it is one of examples, the most basic one.
```
var autobahn = require('autobahn');
var mvConnection = autobahn.Connection({
	url: 'wss://<some address>', 
	realm: 'realm1'
});
mvConnection.onopen = function(session) {
	function onevent(args) {
		console.log("Event:", args[0]);
	}
	session.subscribe('mv.commands.get_coba_product_list', onevent);	  
};
mvConnection.open();
```

It is running on node.js 6.9.2, npm 3.10.9 and with following dependencies

>     "ajv": "^4.10.4",
>     "async": "^2.1.4",
>     "compression": "^1.0.3",
>     "cors": "^2.5.2",
>     "express": "^4.14.0",
>     "helmet": "^1.3.0",
>     "jsonwebtoken": "^7.2.1",
>     "loopback": "^3.0.0",
>     "loopback-boot": "^2.6.5",
>     "loopback-component-explorer": "^4.0.0",
>     "loopback-connector-cloudant": "^1.1.0",
>     "promise": "^7.1.1",
>     "serve-favicon": "^2.0.1",
>     "socket.io": "^1.0.0",
>     "strong-error-handler": "^1.0.1",
>     "winston": "^2.3.0"

This error occurs right after start of server and will crash server. No actions are needed.

**Comment by tomkomt** [comment]
Actually it doesn't matter if I specify realm or not.

**Comment by goeddea** [comment]
Just tested our basic example (https://github.com/crossbario/crossbar/tree/master/crossbar/templates/hello/nodejs) with Node.js 6.9.4 and this works.

The failure you give occurs on the creation of the connection before the realm is parsed.

What does "loopback-boot" do - and does the error occur when you run your code without this?

**Comment by wuhkuh** [comment]
The problem is that you forgot to call 'new', therefore, it is being treated like a function.
