### ISSUE TITLE
No longer compatible with IE11

### ISSUE THREAD

**Issue by jameslai** [crossbario/autobahn-js#257]
The "ws" library Autobahn has a dependency on has committed code which makes it no longer compatible with IE11.

Code in question can be found here:

https://github.com/websockets/ws/commit/44f9e89a501026b0459bad725216dc9500355d63#diff-ac4015dfd17173726807df0406ae1d2bR25

IE11 (and any IE browser below it) cannot handle arrow functions:

http://caniuse.com/#feat=arrow-functions

**Comment by oberstet** [comment]
Oh, this isn't good. Thanks for making us aware!

Are the ws guys aware?

Anything you suggest we should do on Autobahn side (like pinning ws version or what)?

**Comment by jameslai** [comment]
I brought up the issue with the WS team and their response was WS is targeted for Node.js, not the browser:

https://github.com/websockets/ws/issues/993

You can pin the version to 1.1.0 for now, but of course you're off the release/upgrade train after that. Overall it might be prudent to build an abstraction layer and select another websocket library which does target the browser.

**Comment by oberstet** [comment]
I forgot: we are skipping the ws dep on browsers already : https://github.com/crossbario/autobahn-js/blob/master/package.json#L26

So how can this pop up on IE anyway?

**Comment by jameslai** [comment]
Interesting, it doesn't appear that Webpack is honoring this flag. So I presume Autobahn is equipped to use the browser's native Websockets when WS isn't present?

**Comment by oberstet** [comment]
@jameslai Sure. On browsers, there is only native WebSocket (you can't access raw TCP from JS to implement WS yourself).

In any case: I just tested the embedded demo http://crossbar.io/ and it works on IE11 and Edge (Windows 10).

**Comment by leojh** [comment]
We are getting this issue and it's not clear what the actual fix is. Please advice as to what we should do in order to have autobahn-js work on IE11.

**Comment by oberstet** [comment]
@leojh do the demos at https://demo.crossbar.io/ work for you?

**Comment by leojh** [comment]
We were able to resolve the issue by referencing `autobahn.min.js` directly within the app like the demo instead of importing the node package.

**Comment by oberstet** [comment]
Ah, ok. Glad you got it working. Actually, it should work on IE10 too, and using the built-in long-poll WAMP transport over plain old HTTP/1.1, it should also work on IE9. I seem to remember some JS language related IE8 issue which could be fixed too.
