### ISSUE TITLE
Connection breaks after 30min on Android Chrome and Android Opera

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/autobahn-js#261]
Hello! 

I wrote website with autobahn js and it works great on desktop browser. Unfortunately same site does not work on mobile browser. After 30 min after browser goes background, connection dies. No Connection.onclose event fired, but connection not works

I would like to know how we can workaround this issue

**Comment by oberstet** [comment]
Use WebSocket ping-pongs to keep alive the connection. Eg with Crossbar.io, see [here](http://crossbar.io/docs/WebSocket-Options/#production-settings).

> Also: we've got a mailing list for general questions;)

**Comment by alexey2baranov** [comment]
OK! thank you very much
By the way i get error when try to copy paste full config options from manual into my crossbar node

> 2017-03-02T15:28:46+0500 [Controller  21325 crossbar.controller.cli.run_command_start] encountered unknown attribute 'enable_hixie76' in WebSocket options

**Comment by goeddea** [comment]
@alexey2baranov  - We need to update the documentation (https://github.com/crossbario/crossbar/issues/977) in this respect. We no longer support Hixie76.

**Comment by alexey2baranov** [comment]
@oberstet 
I have tested work with production config from manual. Chrome on Android works well now, but Opera sies anyway. 

On the other way this stupid keepAlive emitation works well in both browsers

```javascript
setTimeout(()=>{
    connection.session.call("someLittlePingProcedure")
  },60000
)
```
