### ISSUE TITLE
Feature Request: Resubscribe Option on reconnect

### ISSUE THREAD

**Issue by markope** [crossbario/autobahn-js#265]
Feature description

1. Open Connection with reconnect option on disconnect
1. Subscribe to a topic "with resubscribe option"
1. Network goes down 
1. Reconnect of WAMP-session is established
1. All previous subscriptions with "resubscribe" Option are executed again. 

This is a purely client side feature, so the crossbar meta-api would not help out here. (If you use crossbar as router)

Currently this has to be done manually e.g. by using a pattern like this one [here](http://stackoverflow.com/questions/42879570/reestablish-wamp-subscriptions-after-reconnect/42892763#42892763) 

The Feature would make sense as well for other WAMP Client libraries I guess.
I believe that this is a very common desired behaviour.

**Comment by oberstet** [comment]
FWIW, I don't understand the need for this - can you describe why it is not possible in your app code to centralize all subcribes/registers in a single function (eg onopen itself)? It seems I must be missing something .. never felt a need in writing app code myself for this.

**Comment by goeddea** [comment]
@markope - I'm wondering. This has come up before, but doesn't this still require program logic to handle, i.e. if the connect is an initial connect, do the subscriptions, if it's not, skip this and let Autobahn handle things? In what way is this simpler than just doing the subscriptions on every connect?

**Comment by markope** [comment]
@oberstet The need arises when subscriptions are made dynamically on user interaction. e.g. The user requests a list of objects represented as an js array. This array should however "subscribe" to change events from the backend. 

It's true. Doing it yourself in your app code is not that hard. Just wrap the subscribe in your own function and do your subscription housekeeping in the wrapper. It just feels like this wrapper could be placed nicely in autobahn itself. 

@goeddea I think there is no other program logic involved than an initial subscribe. The workflow I would imagine would be like this : 
1. Subscribe to the already established session with subscribe option at any time you want. 
2. Forget about your subscriptions because you can rely on autobahn to keep them active whenever the session is online.

Anyway this is just a conveniance.

**Comment by oberstet** [comment]
@markope aahh, ok, that is a valid reason. I agree the burden for this should not be put on the app code. thanks for explaining.

Ok, now that I am convinced there is a valid use case, next question is _where_ should this be addressed.

1) implementing sth like this in client libraries
2) implement this router side (we'll have "session resumption" in Crossbar.io upcoming)

With 2), there are couple of advantages, at least these:

* no need to add it to all WAMP client libraries - feature is immediately available in all
* you can have the router remember the events that a client missed while disconnected and let the router redispatch them once the client comes back (this is optional of course)

**Comment by oberstet** [comment]
yet another question in this context is: what about registrations?

while it is "unusual" to have procs registered in browser frontends, it is common for AB/nodejs backend components of course

**Comment by markope** [comment]
but how would the router have knowledge of the client side subscription handlers. I think this can only be solved client side. (Same for registrations)

**Comment by markope** [comment]
Just thinking. Maybe subscriptions and registrations should be "held" at the autobahn connection object level. It should be possible to subscribe/unsubscribe and register/deregister without even opening a session. That would make it possible to subscribe to a topic during a network outage and that would come online as soon as the connection is online. (Maybe somehow related to web service workers) ...

**Comment by oberstet** [comment]
The router does not need to have knowledge of the client side callables attached to subscriptions - this is client side business.

What is required in AB client libraries is a decoupling of the underlying WAMP transport object (which is destroyed when the connection disappears, and recreated from scratch when a new connections is established upon reconnect) from the the WAMP session object.

Currently, in AB JS, this isn't the case: a new Session object is created upon reconnect. However, in AB JS, this could be fixed without an API breakage.

In AB Py, this cannot be done in the current API, as I made a design mistake: I used inheritance (user code derives from ApplicationSession). this is bad. composition is the way to go. To my excuse, AB Py was designed to fit naturally into Twisted - and Twisted made the same mistake long ago. the core devs changed their mind, and it is now established view that inheritance is to be avoided, and composition is the way to go.

I would go even further: OO sucks. functional programming with composition is the way to go .. applies to all languages. of course some language suck at "functional" like Java. I don't care. JS is good enough in this respect. Python is very good. C++ also (but a headfuck in general).

FWIW, I won't support a "quick fix" in AB. I dont care how easy a quick fix _could_ be implemented. I am concerned about design. whatever we do, it needs to be well designed and sustainable. that includes the pattern must be similar in all ABs.

**Comment by kuema** [comment]
We have faced a similar use case when implementing a set of WAMP nodes for Node-RED. We ended up managing all subscriptions/registrations in our client node. That way we could add a subscription/registration even if the connection has not been established yet. As soon as the session is available, we bulk-register/subscribe our stored elements. That works seamlessly for connection losses too.

The [Wampy](https://www.npmjs.com/package/wampy) client lib already supports something like this by hiding the underlying session from the user, allowing you to register/subscribe at any time.

**Comment by paulpdaniels** [comment]
FWIW this was something I did with [rx-wamp](https://github.com/paulpdaniels/rx.wamp) as well. Personally I lean more toward *not* having this kind of specific behavior in Autobahn, but providing enough of an interface for clients to create it if necessary.

**Comment by oberstet** [comment]
won't fix - I agree with others, if you need it, the app level is the right way to do for different reasons
