### ISSUE TITLE
Connection loss: reject outstanding RPC

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#27]
When a caller initiates a RPC, it might want to specify that the promise returned should be automatically rejected when the connection is lost.

The main problem is API .. see https://github.com/tavendo/AutobahnJS/issues/24

**Comment by davidwdan** [comment]
:+1:

**Comment by oberstet** [comment]
here is a dup, but with better description https://github.com/crossbario/autobahn-js/issues/360

closing this one ..
