### ISSUE TITLE
Cannot use AWS CDN

### ISSUE THREAD

**Issue by eddysantos** [crossbario/autobahn-js#270]
I had been using the AWS CDN for a few weeks now, and all of a sudden I am getting the 403 Forbidden error.

**Comment by oberstet** [comment]
https://groups.google.com/forum/#!topic/autobahnws/aHxWgImJvCY

**Comment by eddysantos** [comment]
I was not aware of that issue. My bad and thanks for the input.

**Comment by oberstet** [comment]
np, sorry for the hassles - I saw no other way than "hard deactivate" .. many people that now run into this never have been on the mailing list nor had any contact with us before .. so no way of contacting them before

**Comment by eddysantos** [comment]
I am now hosting it for my app on my own, but my older code for some reason is no longer working. Any recommendation on where to get support? (I'm really new with WAMP sessions)

**Comment by oberstet** [comment]
you can find all releases of AutobahnJS, also older ones in the repo https://github.com/crossbario/autobahn-js-built

each release is properly tagged. so just git checkout the release you want.

there is zero code change between the releases in above repo, and the files we formerly hosted on AWS S3

**Comment by eddysantos** [comment]
Got it ... I found the problem. I am using Ratchet, and apparently I need the Legacy 0.8.2 Autobahn JS Version, but I can't find it on your site (I believe it was part of the Bucket you took out). I am trying to look for it here: http://autobahn.ws/js/reference_wampv1.html 

Do you have any other link where I could get it from? 

I plan on eventually upgrading the code and keep my site up to date, but for right now, I would like to have the site working again. 

Sorry again for all the trouble. 

Thanks!

**Comment by oberstet** [comment]
Uups. I see. Nope, I don't have it anymore. It's gone - it would take me some time to recreate from the sources which I don't have. This stuff is deprecated for multiple years now.

I wasn't aware that page (http://autobahn.ws/js/reference_wampv1.html). Maybe Ratchet has it still around.

**Comment by oberstet** [comment]
FWIW, the sources for this old version are in _this_ repo (but not in the "built" repo). So you should be able to get / built it from _this_ repo (it is properly tagged).

**Comment by oberstet** [comment]
I am sorry, this was unintentional, but I think I gave reasons of how/why this happened. And officially,  we haven't support WAMPv1 for long time now.

**Comment by eddysantos** [comment]
I know buddy, I understand. I actually don't blame you, rather my currently poor developing skills. I'll either figure out the way to build the old version, or give the alternatives you have provided in other threads (Thruway).

**Comment by kplaczek** [comment]
@eddysantos yesterday I was in the same position as you. I managed to find an 0.8.2 version here https://github.com/sergeyvolkov/autobahn-old this is the same file as the one that was in this link
> https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.js

**Comment by eddysantos** [comment]
Damn!!! I came across that file but for some reason it gave me an error and I didn't pursue it. Thanks for putting it back in my mind... it's back to normal now!! 

I guess I should still look into upgrading the technology of the site, but at least I don't have to kill myself re-coding the entire web-socket portion (I'm still very new at this WAMP stuff).

Thanks again man!!
