### ISSUE TITLE
S3 Bucket Access denied

### ISSUE THREAD

**Issue by M1ke** [crossbario/autobahn-js#271]
It's currently not possible to load any of the JS files with built Autobahn from the Autobahn website as both the zipped hotlink for dev and the downloadable files for production are access denied. Is it possible to place these built files in the repository (or if they already are, apologies for not finding them and may you send me a link?)

**Comment by oberstet** [comment]
https://groups.google.com/forum/m/#!topic/autobahnws/aHxWgImJvCY
