### ISSUE TITLE
Enable AUTOBAHN_DEBUG with es6 modules

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/autobahn-js#272]
I tried this code, but it doesn't seem to work:
```
const AUTOBAHN_DEBUG = true
window.AUTOBAHN_DEBUG = true

import autobahn from 'autobahn'
```
I think it should print something if debug mode is successfully activated? https://github.com/crossbario/autobahn-js/blob/df3500fd536016e52a5f273c1303e5d870ce1dd4/lib/autobahn.js#L24

**Comment by oberstet** [comment]
we have a mailing list
