### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by vytautasgimbutas** [crossbario/autobahn-js#274]
Hello,
this link gives 403 forbidden https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.js

**Comment by oberstet** [comment]
https://groups.google.com/forum/m/#!topic/autobahnws/aHxWgImJvCY

**Comment by vytautasgimbutas** [comment]
http://crossbar.io/autobahn/
links should be changed in this case. try clicking on "Download"

**Comment by oberstet** [comment]
@vytautasgimbutas uups, sorry. yeah, the link is wrong.

**Comment by vytautasgimbutas** [comment]
@oberstet thanks. I was still using version 0.8.2. can i download this version from somewhere? I see that autobahn-built-js repository does not have a tag with this version.

**Comment by oberstet** [comment]
No, this is deprecated: https://github.com/crossbario/autobahn-js/issues/270#issuecomment-288835732
