### ISSUE TITLE
Support for custom transports

### ISSUE THREAD

**Issue by RationalCoding** [crossbario/autobahn-js#275]
WAMP is transport agnostic, so it makes sense to expose a way to register custom transports without needing to manually add them to configure.js and rebuild. I know this has been mentioned previously, but I thought I would open a specific issue for it.

WebRTC and Bluetooth Low Energy are just a few examples. If this seems like a good idea, I will be glad to help out.

**Comment by oberstet** [comment]
Neither WebRTC nor BLE support the required semantics. No, this doesn't make sense to expose
