### ISSUE TITLE
AutobahnJS embed and license issue (?)

### ISSUE THREAD

**Issue by glenfant** [crossbario/autobahn-js#289]
Hi,

I proudly pushed to Github a demo application under MIT license (Django + Crossbar + Autobahn|jS), at https://github.com/alterway/wamp-polls and to make the installation process easier (no "bower" stuff), I made a copy fo the minifies autobahn.js stolen here https://github.com/crossbario/autobahn-js-built .

Is this allowed by the Autobahn|JS license ? Should I mention someting about it in the README ?

Thanks for this great piece of software.

**Comment by goeddea** [comment]
@glenfant - Your are allowed to do this. You can do with Autobahn|JS whatever you want (as long as you don't remove the MIT license notice). In fact, the Autobahn|JS builds we offer are intended to be used by you like this, hosted yourself etc.

**Comment by oberstet** [comment]
@glenfant Cool!! For a demo, it is also very well documented. Which is an additional plus. This really deserves some attention / could be interesting to more devs. Do you mind if we link to it somewhere from our docs? @goeddea This would be of interest to Web developers, as well as Python/Django developers in particular. Maybe a central "external resources" page might be worth starting, collecting all the splintered bits and links ..

I also noticed https://www.alterway.fr/ - I lack the language skills to really read it, but it seems a company providing advanced Web development/consulting services? Are you affiliated? Want to be listed on our commercial site (as in "can do Autobahn/Crossbar.io/WAMP projects")? Pls drop me a line if this might be interesting to you : tobias dot oberstein at crossbario dot com

**Comment by glenfant** [comment]
Hi @oberstet ,

(a) Proud to be listed in the Crossbar heroes though I'm only a noob++ in that domain.

(b) I transmit that link to my favorite commercial manager who will - hopefully - reply positively.

Have a good evening
