### ISSUE TITLE
feature request: autobahn.Connection extends EventEmitter

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/autobahn-js#292]
Hello! 

It come be very helpfully when Connection extends EventEmitter. 
First benefit is ability to have many handlers on each event. Second benefit is ability to use `once` method which we would like to use when app starts and first cookie auth performed immediately.

thanks

**Comment by wuhkuh** [comment]
If you consider this, you could also consider using [EventEmitter2](https://github.com/asyncly/EventEmitter2). Benchmarks seem solid too:

> EventEmitterHeatUp x 3,728,965 ops/sec \302\2610.68% (60 runs sampled)
EventEmitter x 2,822,904 ops/sec \302\2610.74% (63 runs sampled)
EventEmitter2 x 7,251,227 ops/sec \302\2610.55% (58 runs sampled)
EventEmitter2 (wild) x 3,220,268 ops/sec \302\2610.44% (65 runs sampled)
Fastest is EventEmitter2

**Comment by oberstet** [comment]
won't fix: this is an intrusive change to the whole library API (moving from callbacks for connection handling to an observer pattern), and we don't have the time/resources/motivation for that
