### ISSUE TITLE
Incomplete construction

### ISSUE THREAD

**Issue by wuhkuh** [crossbario/autobahn-js#294]
The platform the code is running on: Node 7.9.0.
I'm using the following code:

```js
const autobahn = require('autobahn')
const wsurl = 'wss://URL'

class API {
  constructor () {
    this._connection = new autobahn.Connection({ url: wsurl, realm: 'realm1' })
  }
}

console.log(new API()._connection)
```
If you run this code, you can see some properties missing, like the _transport property, containing the onopen and onclose functions. Moreover, if you add this line:
```
new API()._connection.onopen(console.log('opened!')
```
it will error out: `TypeError: this._connection.onopen is not a function`.
Have I made a mistake on my end or is this, as I suspect, undesired behavior?

**Comment by oberstet** [comment]
The `onopen` and `onclose` properties are supposed to be set by the user (these are your callbacks) - if you don't set them, Autobahn will not call them. In above, you manually try to call them from outside the library, which doesn't make sense ..

**Comment by wuhkuh** [comment]
The solution was indeed to set the functions myself. At first I tried to implement it like this, as I imagined it to be like an EventEmitter with the first parameter already set, therefore only requiring a callback. When debugging I noticed more properties missing, so I thought it might be a bug during construction, but I understand this is intended behavior.

I'm closing this issue.
