### ISSUE TITLE
Payload transparency / client side codecs

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#297]
Essentially, port `ApplicationSession.set_payload_codec` and related bits.

**Comment by agronholm** [comment]
I am working on this but I have other things on my to-do list too.

**Comment by oberstet** [comment]
I don't think we need this in the form indicated? should we close it? @om26er

**Comment by om26er** [comment]
Yeah, we dont need it for XBR stuff, we took a different approach.
