### ISSUE TITLE
Adding support for React Native

### ISSUE THREAD

**Issue by furball514** [crossbario/autobahn-js#305]

**Comment by beerteam** [comment]
Hello. Have you solved the problem?

**Comment by beerteam** [comment]
I use minified version of autobahn, from recommendation
Its ok, but autobahn not connect to the server, say:

`could not create WAMP transport 'websocket': TypeError: undefined is not an object (evaluating 'b.process.versions.node')`

Autobahn is very cool. With ReactNative it will be the most cool!
@oberstet, how can I solve the problem with ReactNative
