### ISSUE TITLE
UgilfyJS - Unexpected token: name (Simple)

### ISSUE THREAD

**Issue by adrienfourel** [crossbario/autobahn-js#307]
When adding autobahn to my vue-js app, I have an error when trying to build for production using webpack 2.6 and UglifyJS :

`ERROR in static/js/app.bdcd88ac9fe0000fe77f.js from UglifyJs`
`Unexpected token: name (Simple) [./~/cbor/lib/simple.js:9,0]`

It seems to come from this lib : [hildjj/node-cbor](https://github.com/hildjj/node-cbor/)

I created an issue there too but I wanted to know if someone had encountered it and resolved it ?

https://github.com/hildjj/node-cbor/issues/57

**Comment by adrienfourel** [comment]
Just noticed it's a duplicate.

**Comment by codegastudio** [comment]
@adrlen I had the same problem 
downgrade to autobahn 0.11.2 allow to pass compilation with --prod flag but this is not the final goal

**Comment by adrlen** [comment]
Thanks, it works indeed.

Though I'm not very confident either to work with an older version of the lib.

**Comment by ruaanvds** [comment]
I'm running into this exact same issue (using Webpack v2 + React-based application). Pretty annoying, since my Jest test suite doesn't work with Autobahn 0.11.2.

**Comment by oberstet** [comment]
Pls see my comment https://github.com/crossbario/autobahn-js/issues/306#issuecomment-310606346

Please bug upstream "cbor" or UglifyJS .. nothing we can do here.

**Comment by Dodobibi** [comment]
If you don't use CBOR, and you wan't to use the last version of autobahn, you can add this in the webpack module loaders :

`{
          test: require.resolve("cbor"),
          loader: "null-loader"
        }`

This replace the cbor library by `empty`

**Comment by adrlen** [comment]
Then I have this error when running webpack dev compilation :

```
ERROR  Failed to compile with 2 errors

This dependency was not found:

* cbor in ./~/autobahn/lib/autobahn.js, ./~/autobahn/lib/serializer.js
```
