### ISSUE TITLE
Support call cancelling

### ISSUE THREAD

**Issue by chrisbarber** [crossbario/autobahn-js#309]
According to [this line in the code][1] it looks like autobahn-js does not support call cancelling. I also do not see any reference to it in the [Progressive Results section of the API doc][2].

Is it correct that there currently is no way for an autobahnjs caller to cancel a progressive call? Is this a planned feature?

Unsure of how this would even be designed. One way might be something like this:

    var d = session.call('com.myapp.longop', [10], {}, {receive_progress: true});
    d.cancel()

Which would mimic the [autobahn|python style][3]. But I believe `d` is just a standard deferred from whichever promise library is being used. Perhaps

    var d = session.call('com.myapp.longop', [10], {}, {receive_progress: true});
    d.reject()

could be used and `session.call` would have added an `onReject` handler which will send a `WAMP.CANCEL` message in the case of `receive_progress: true`?

  [1]: https://github.com/crossbario/autobahn-js/blob/37fb3232ff0842c166ef1d86265602d2b1292d26/lib/session.js#L34
  [2]: https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#progressive-results
  [3]: https://github.com/crossbario/autobahn-python/blob/224370cd9dda312fc0583b61ed416b3f4d0e00d0/docs/work/programming.rst#canceling-calls

**Comment by chrisbarber** [comment]
`d.reject(...)` could be supplied with a rejection reason indicating that it was a callee cancellation, as well as the WAMP CANCEL options:

`CANCEL.Options.mode|string` == "skip" | "kill" | "killnowait"`

Inside `Session.call`, if `options.receive_progress`, a [`promise.catch`](https://github.com/cujojs/when/blob/master/docs/api.md#promisecatch) could be added, with a `predicate` testing for the aforementioned "callee cancel" rejection reason. The supplied `onRejection` would already know the established [request id](https://github.com/crossbario/autobahn-js/blob/37fb3232ff0842c166ef1d86265602d2b1292d26/lib/session.js#L1209), and would receive the options as parameter, which is enough to construct the WAMP CANCEL message:

`[CANCEL, CALL.Request|id, Options|dict]`

And send with `_send_wamp`.

**Comment by oberstet** [comment]
You are right that canceling a progressive call is currently not supported by the library. This is definitely a gap. Progressive results however are supported: they are finally processed here and provided to user code here https://github.com/crossbario/autobahn-js/blob/master/lib/session.js#L684

**Comment by Jopie64** [comment]
I drafted a commit Jopie64/autobahn-js@2e75302c0f3bcd528119633a46f1e72d472864ae
I think it is a really straightforward way to be able to cancel a call, but it is also kinda hacky. Would this be accepted this way? If not, what else is needed?
In our company we like to use progressive calls as a way to implement the Rx cold observable paradigm over WAMP. But the only missing feature in this paradigm is to be able to 'unsubscribe' from it. Being able to 'Cancel' a progressive call would make this possible.
