### ISSUE TITLE
Published private key?

### ISSUE THREAD

**Issue by nyxxxie** [crossbario/autobahn-js#310]
Was casually browsing your repo and noticed you [published a private key for your service](https://github.com/crossbario/autobahn-js/blob/master/.crossbar/key.priv).  Not sure how your service uses these, but traditionally private keys are meant to be... private.  Figured I'd let you know in case this was unintended.

**Comment by oberstet** [comment]
Thanks for keeping eyes open and letting us know. 

However, this is intentional, and no problem: of course you wouldn't use that key in any production system. It's just there for added convenience in testing/development ..
