### ISSUE TITLE
Electron: shared autobahn session can't return values from renderer via RPC

### ISSUE THREAD

**Issue by a-sync** [crossbario/autobahn-js#315]
Hi, 
maybe my approach to use the session in both processes is the problem, but i didn't find any other way to solve this, any input is welcome. :) 
This anomaly only happens when trying to return something from a function registered in the renderer process. All other pubsub and rpc calls work fine afaik, including the incoming values for the same function. 

Steps to reproduce:
1. The connection is created in the main process, and the session is stored in a global variable.
2. This global variable is loaded in the renderer process via remote.getGlobal() and used to register a local function to a topic that returns some simple javascript object.
3. A call is made to the registered topic from an outside service, which expects some value to be returned.
4. The call resolves, but the returned value is always null.

To reproduce and test this (and every possible combination of pubsub and rpc calls to and from the main and the renderer process) i created the following two packages. 

https://github.com/a-sync/electron-autobahn-test
https://github.com/a-sync/service-autobahn-test

The electron app uses the previously described method to share an autobahn session, and provides a simple gui to control the following:
 * publish and call from the main process (triggered via ipc) (handled by the service)
 * publish and call from the renderer process (handled by the service)
 * trigger publish and rpc calls from the service (handled by the main and the renderer process)

Every publish, and every call sends an object with multiple keys and nested values, and every call returns a similar object. Everything received or returned, is sent to console.log().

Both packages include the same .crossbar folder and config file, either one can be used to spin up the crossbar server with the necessary settings. 
After installing the dependencies, starting the crossbar server and running both programs (with npm start), the issue can be reproduced by clicking on the **service.do.call** button. This will signal the service, to do two rpc calls, one registered in the main process, and one in the renderer process. 
![electron-autobahn-test](https://user-images.githubusercontent.com/14183614/27773161-ed803668-5f73-11e7-952e-81106c406743.png)

The results from the returned values can be observed in the console of the service.
Notice that the call to **test.main.register** receives the object returned, while the call to **test.renderer.register** resolves to null.

Thanks for reading. :grimacing:

**Comment by oberstet** [comment]
Ok, so to understand correctly:

1. you want to share an ABJS session object (which holds a WAMP-WebSocket connection under the hood) between 2 electron processes (eg main and some renderer)
2. you have created test cases for all combinations (that is in particular sharing between main and a renderer process) and these all pass

But your actual program fails.

Right?

tbh, I have no clue;) what I would say without looking deep into this: rgd 1. why do you want to do that? I would question that .. why share a session in the first place?

> here is a possibly related consideration we have in a different project using ABJS in little webkit/webviews in a Qt5 / pyside2 application. instead of each webview/ABJS having its own WAMP connection, why not have 1 "physical" / multiplexed connection on the enclosing python/qt5 app? to do that, we would need a 1) internal process-process WAMP transport to talk WAMP from the main process and the webviews and 2) WAMP multiplexing. anyways .. this is qt5, not electron.

**Comment by a-sync** [comment]
@oberstet 2. all tests pass **EXPECT** returning values or resolving properly from a handler registered in the renderer process. On the caller's end it will resolve immediately, and always with null as result. (Sending data towards the handler registered in renderer works fine however.)  

To be clear the node integration is set to false, and the ab session is passed via remote.getGlobal('absession')

It's all in the working example, your welcome to test it yourselves.

To work around this i just avoided any logic that depended on registered handlers in the renderer returning values. Running the registration in the main process and using an ipc proxy function to pass on data and return values also works ofc.

**Comment by oberstet** [comment]
> 2. all tests pass EXPECT returning values or resolving properly from a handler registered in the renderer process.

Ok, I would have expected to lead to problems;) Don't use/share a single WAMP connection over different threads or processes.

Eg in autobahn-python using twisted, when you have a main thread handling a WAMP connection (opening and registering procs), when you then want to run stuff on a different thread from within the body of an event handler or registered procedure, you have to use `deferToThread`. When you want to eg publish from such a thread different from the main thread that holds the WAMP connection and registrations, you have to use `callFromThread` to call methods on the session object living on main thread. In this case it is about coordination between access to data shared between threads in a single process.
