### ISSUE TITLE
Error during WebSocket handshake Unexpected response code 403 

### ISSUE THREAD

**Issue by craigcosmo** [crossbario/autobahn-js#316]
I make a plain simple connection between browser and a server via socket.

I keep getting this error

![screen shot 2017-08-02 at 5 12 14 pm](https://user-images.githubusercontent.com/538657/28869345-9740c024-77a6-11e7-9c6b-638608260833.png)

This is code
```html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script>
		import autobahn from 'autobahn'
		let wsuri = 'wss://api.poloniex.com'
		let connection = new autobahn.Connection({
			url: wsuri,
			realm: 'realm1'
		})
		connection.onopen = function (session) {
			function marketEvent (args,kwargs) {
				console.log(args)
			}
			session.subscribe('BTC_USDT', marketEvent)
		}

		connection.onclose = function () {
			console.log('Websocket connection closed')
		}

		connection.open()
	</script>
</head>
<body>

</body>
</html>
```

That's all the code. I run this code in browser, got the errors

**Comment by ProExpertProg** [comment]
Did you manage to solve the problem?

**Comment by craigcosmo** [comment]
sits solved. this is because I provided the wrong credential server denied.

**Comment by ProExpertProg** [comment]
Because I am receiving the same error code when using the sample code from the poloniex api docs
