### ISSUE TITLE
Karma unit test not works. Cannot read property 'unmask' of undefined

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/autobahn-js#317]
Hello! I just started new Autobahn project and get this error when start Karma.

My configuration is
OS: linux, Windows
nodejs 7.10.0, 8

I was opened same issues hire few month ago 
https://github.com/vuejs-templates/webpack/issues/728 
https://github.com/karma-runner/karma/issues/2593

and found that temporary workaround for this issue is to use `--no-optional` option
`npm install --no-optional`

Thanks!

> > karma start test/unit/karma.conf.js --single-run
> 
> 09 08 2017 20:54:33.179:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
> 09 08 2017 20:54:33.182:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
> 09 08 2017 20:54:33.196:INFO [launcher]: Starting browser PhantomJS
> 09 08 2017 20:54:36.098:ERROR [karma]: TypeError: Cannot read property 'unmask' of undefined
>     at Receiver.unmask (C:\unmask-research\node_modules\ws\lib\Receiver.js:306:46)
>     at Receiver.finish (C:\unmask-research\node_modules\ws\lib\Receiver.js:505:25)
>     at Receiver.expectHandler (C:\unmask-research\node_modules\ws\lib\Receiver.js:493:33)
>     at Receiver.add (C:\unmask-research\node_modules\ws\lib\Receiver.js:103:24)
>     at Socket.realHandler (C:\unmask-research\node_modules\ws\lib\WebSocket.js:825:20)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:191:7)
>     at readableAddChunk (_stream_readable.js:178:18)
>     at Socket.Readable.push (_stream_readable.js:136:10)
>     at TCP.onread (net.js:563:20)
>

**Comment by oberstet** [comment]
This is related to ws and node version I think (https://github.com/crossbario/autobahn-js#nodejs-development). I don't think Autobahn is wrong, or that we can do anything about these issues.
