### ISSUE TITLE
es6 promise v.s. whenjs: progress

### ISSUE THREAD

**Issue by joggienl** [crossbario/autobahn-js#319]
Even though not in the official Promise A+ spec, whenjs has (deprecated!) support for progress like results trough calling `notify`.

Are there plans to improve this behaviour?

I currently have a use case for using progressive results. But if you set the Connection options to `use_es6_promises` things break: https://github.com/crossbario/autobahn-js/blob/10797c79adf06a6d8ab1ddc4c34a51c04bbbcd43/lib/session.js#L686.

I have a specific RPC which I need to call with `{receive_progress: true}`. It will throw an error on this line.

I'm not sure yet what would be a better way to be able to do progressive results (it is part of the WAMP spec after all). Curious to know I've you have any idea on this already. I don't think it is wise to wait until whenjs drops this from their lib ;-)

**Comment by Jopie64** [comment]
rxjs observables would be ideal for progressive call results!
I have a use case for progressive results too, and it would be great when they would be implemented with observables instead of with promises.

**Comment by oberstet** [comment]
progressive results RPC do work and are tested in our CI: https://github.com/crossbario/autobahn-js/blob/master/test/test_rpc_progress.js
