### ISSUE TITLE
failed: Establishing a tunnel via proxy server failed.

### ISSUE THREAD

**Issue by inovamatic** [crossbario/autobahn-js#320]
Hello,

I have a webapp in production with a crossbar io server and we connect to it using autobahn js.
The crossbar io has 2 websockets transports, no web.
When an android device is connected through wifi all works fine.
When it connects via LTE depends on the provider.
Vodafone mobile connected devices give a "failed: Establishing a tunnel via proxy server failed." error.
One the other 2 Portuguese moblie providers all goes smooth.

Any suggestions of might be the problem? Anyone knows a solution?
Thanks

**Comment by davidwdan** [comment]
What port is crossbar running on?

**Comment by inovamatic** [comment]
Port 9090.

Already tried a web transport too but with no success.

**Comment by inovamatic** [comment]
I just tried a new debian 8 VPS fresh installed with just only the default crossbar template with counter publishes.
Same behavior from the Vodafone Portugal over LTE.

Image of the chrome debug.

![image](https://user-images.githubusercontent.com/17597148/30887722-8d0ca39a-a314-11e7-8bf1-4889552ad7a0.png)

**Comment by inovamatic** [comment]
Solved,

Changed port from 8080 to 443 and it works.
Vodafone somehow filters websockets on none standard ports.

I hope this thread can help someone with the same problem.

**Comment by BrixSat** [comment]
I have the same issue. This is stupid I know. It has to have a nice solution.
