### ISSUE TITLE
Add support for React Native execution environment

### ISSUE THREAD

**Issue by pmlt** [crossbario/autobahn-js#321]
Hello, 

First of all, I'd like to thank you all for your great work. Autobahn (and WAMP in general) is terrific technology, and we've used it successfully in our web projects in the past.

However, we've run into a serious issue in our latest project, which is based on [React Native](https://facebook.github.io/react-native/) technology: Autobahn.js does not appear to support the React Native execution environment (it crashes). This has forced us to fallback on other Javascript WAMP implementations which are not nearly as robust as the reference implementation.

Since React Native actually supports Websocket (ref: https://facebook.github.io/react-native/docs/network.html), it should be relatively easy to support this environment.

Thanks again for your great work!

**Comment by oberstet** [comment]
@pmlt if AutobahnJS is able to crash this run-time, there is likely a bug in the latter.

**Comment by pmlt** [comment]
Sorry, I should have been clearer.

The problem is at build-time, not run-time. When I build for Android, I get the following issue:

Unable to resolve ../when" from ".//node_modules/when/dist/browser/when.js`: could not resolve `/home/pmilot/dev/wamp-sample/node_modules/when/dist/when' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]},"type":"bundling_error"}"

Steps to reproduce:

1. Use `create-react-native-app` to create a blank react-native app
2. Add autobahn package to the project (I was using yarn, so I used the command `yarn add autobahn`)
3. Add the line `import Autobahn from 'autobahn';` at the top of `App.js`
4. Try to build the project by running `yarn start` and attempting to load the app on a device - Boom! The error above appears and the app doesn't compile.

**Comment by jakeopena** [comment]
I had the same issue.

**Comment by oberstet** [comment]
PRs are welcome! We don't use React, so eg me, I have zero clue about this stuff - and no time to look into.

**Comment by dodikuswono** [comment]
Detecting React Native can be done with:
``if (navigator.product === 'ReactNative')

I ended up using [wamp.js2](https://github.com/patotoma/wamp.js2), stripped-down version of autobahn without crypto-js, when, ws, msgpack-lite.

**Comment by oberstet** [comment]
closing as dup of https://github.com/crossbario/autobahn-js/issues/372 - will be tracked via the latter issue
