### ISSUE TITLE
Automatic retry authentication if authentication procedure is not registered yet

### ISSUE THREAD

**Issue by cyxou** [crossbario/autobahn-js#322]
As documented [here](https://crossbar.io/docs/Challenge-Response-Authentication/#dynamic-credentials), my Crossbar server is configured to delegate authentication to the **com.example.authenticate** procedure which is registered by a separate Authentication node (not the [guest node](https://crossbar.io/docs/Guest-Configuration/)). It may happen so that Authentication node needs to be restarted and while being restarted, a client could try to connect to the server and be rejected with the  'wamp.error.no_such_procedure' error. In such case, no reconnection attempt is made by autobahn-js. It would be cool if autobahn could spot that and reconnect.

**Comment by goeddea** [comment]
Edited the title to better reflect what you want.

**Comment by oberstet** [comment]
this is app level business
