### ISSUE TITLE
vuejs karma unit test include autobahn

### ISSUE THREAD

**Issue by zhuyinjing** [crossbario/autobahn-js#324]
hi,
i use vuejs ,and i want to unit test my code.and my home.vue had import autobahn,and in my home.spec.js to unit test home.vue.
when i run  `npm run unit` it shows error 
`SourceMap position not found for trace: undefined
     null is not an object (evaluating 'this.autobahnSession.call')
`
and i also import autobahn in my test code.
how should i do to unit test when my home.vue function has autobahn...
thanks so much!

**Comment by zhuyinjing** [comment]
@oberstet can you help me?

**Comment by goeddea** [comment]
This is an issue tracker, not a support forum. Closing.

You better ask this question on the forum - https://groups.google.com/forum/#!forum/autobahnws
