### ISSUE TITLE
UNhandled rejection with invalid url

### ISSUE THREAD

**Issue by riksnelders** [crossbario/autobahn-js#327]
`Potentially unhandled rejection [1] {"error":"wamp.error.invalid_uri","args":["subscribe for invalid topic URI 'com.something..live'"],"kwargs":{}} (WARNING: non-Error used)`

Notice the wildcard..

**Comment by oberstet** [comment]
wildcard subscribes to work - this is explicitly tested in our CI: https://github.com/crossbario/autobahn-js/blob/master/test/test_pubsub_wildcard_sub.js
