### ISSUE TITLE
Can Autobahn in browser work with remote server/router?

### ISSUE THREAD

**Issue by lockevn** [crossbario/autobahn-js#333]
Hi,
I use Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Running Autobahn 17.5.2

It always says: "Websocket connection closed" when I try to connect to wss://demo.crossbar.io/ws
Where it works on https://demo.crossbar.io/votes/index.html

**Does it not work with remote router?**

In fact, I try to connect to wss://api.poloniex.com, it fails as well.

**Comment by oberstet** [comment]
this is an issue tracker, not a user forum
