### ISSUE TITLE
Production build not working

### ISSUE THREAD

**Issue by filipefreitas82** [crossbario/autobahn-js#341]
In my angular app I've been using this lib and everything works fine in development.

After compiling to production (ng build --prod)  I get the following RTE:
```
Uncaught TypeError: (intermediate value)(intermediate value) is not a function
at when.js:1008
at Object.12.../apply (when.js:753)
at o (when.js:13)
at when.js:13
at when.js:2948
at when.js:3133
at Object.32../lib/Promise (when.js:2944)
at o (when.js:13)
at when.js:13
at Object.1.../callbacks (when.js:16)
```

Using:
````
Angular CLI: 1.7.1
Node: 8.9.0
OS: darwin x64
Angular: 5.2.6
autobahn: 17.5.2
````
The only workaround is to compile without optimizing: ng build --prod --aot=false

Anyone has this issue?

**Comment by oberstet** [comment]
sorry, OT

**Comment by pmomot** [comment]
@filipefreitas82 have you found a way to solve this instead of disabling `aot`? I'm experiencing the same.
