### ISSUE TITLE
Better error message with syntax error on Websocket URL

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/autobahn-js#343]
I used the URL `ws:<ip>` instead of `ws://<ip>`, which works on Firefox and Chrome, but gives a cryptic `could not create WAMP transport 'websocket': SyntaxError` on Edge. Maybe catch the exception at creation and rethrow with more context, like `syntax error in the WS URL`?

https://github.com/crossbario/autobahn-js/blob/79b093bf47f6ff3e2fd50f42fce20578150baaf9/lib/transport/websocket.js#L161-L165

**Comment by oberstet** [comment]
Uh, ok: `ws:<ip>` should be an error on all browsers (so MS Edge is right here), and yeah, an error message like "invalid WebSocket URL" would be nice!

**Comment by oberstet** [comment]
the error message comes from the browser (or nodejs/`ws`) - guess those are the right upstream projects to actually bug;)

**Comment by Yamakaky** [comment]
My point is still valid, the error message is cryptic.
