### ISSUE TITLE
Request to remove optional dependencies

### ISSUE THREAD

**Issue by stanleyxu2005** [crossbario/autobahn-js#345]
I have searched the code, have not any direct usage of these two optional dependencies. Could you consider to remove them? 
https://github.com/crossbario/autobahn-js/blob/c3a800a359838fbbc1b47af55cd122fa01dd0de4/package.json#L20-L23

Here is my sad story: 
I tried to install autobahn with `npm install autobahn --prod --no-optional`, but npm (percisely node-gyp) still tried to build `utf-8-validate` and` bufferutil` from the scratch. Usually it's fine, but I'm behind a proxy, the gyp build will always fail. If they are irrelevant, I'd vote for removing them.

**Comment by oberstet** [comment]
those optionals deps can be used on nodejs (accelerate stuff)
