### ISSUE TITLE
Latest version of ws (>=5.1.0) breaks autobahn.js

### ISSUE THREAD

**Issue by vdiez** [crossbario/autobahn-js#347]
After installing latest version of ws, autobahn is unable to connect to crossbar server:

```
upop@host:~/node_collectd$ npm install ws@5.1.0
npm WARN node_collectd@1.0.0 No description
npm WARN node_collectd@1.0.0 No repository field.

+ ws@5.1.0
updated 1 package in 1.342s
upop@host:~/node_collectd$ node
> let autobahn = require('autobahn')
undefined
> let wamp = new autobahn.Connection({url:'ws://10.67.19.64:8080/ws', realm:'realm1', max_retries: 0});
undefined
> wamp.onopen = ses => {console.log("connected")}
[Function]
> wamp.onclose = (reason, details) => console.log(reason, details);
[Function]
> wamp.open()
undefined
> unreachable { reason: null,
  message: null,
  retry_delay: null,
  retry_count: null,
  will_retry: false }
unreachable { reason: null,
  message: null,
  retry_delay: null,
  retry_count: null,
  will_retry: false }
```

Crossbar server output:

```
2018-04-11T14:57:49+0200 [Router      21292] failing WebSocket opening handshake ('This server only speaks WebSocket subprotocols wamp.2.cbor.batched, wamp.2.cbor, wamp.2.msgpack.batched, wamp.2.msgpack, wamp.2.ubjson.batched, wamp.2.ubjson, wamp.2.json.batched, wamp.2.json')
2018-04-11T14:57:49+0200 [Router      21292] dropping connection to peer tcp4:10.67.64.67:36909 with abort=False: This server only speaks WebSocket subprotocols wamp.2.cbor.batched, wamp.2.cbor, wamp.2.msgpack.batched, wamp.2.msgpack, wamp.2.ubjson.batched, wamp.2.ubjson, wamp.2.json.batched, wamp.2.json
```

Something seems to have change from 5.0.0, which works correctly (right now I'm pinning my env to it) and 5.1.0 and doesn't seem to be an error on your side, so this is more a heads up for you than an actual bug.

Thanks!

**Comment by vdiez** [comment]
[Here are the changes between those 2 versions](https://github.com/websockets/ws/compare/d3af50627de62b0d8b9c42d915e8c6a426238363...7c74567b974b79253ac32aac8f7d3dcb3e6d17e8). I lack the knowledge of WebSocket standards, so not much I can workout from there by myself anyway.

In any case, I will continue using 5.0.0 until further news. Thanks again!

**Comment by oberstet** [comment]
well, seems like ws doesn't forward the subprotocol anymore .. if that is the case, this is a bug in ws.

I don't have the time to dig deeper .. but the issue must be around here

https://github.com/websockets/ws/compare/d3af50627de62b0d8b9c42d915e8c6a426238363...7c74567b974b79253ac32aac8f7d3dcb3e6d17e8#diff-13a0e23b4df05bd40179ab73312bf77bL53

**Comment by vdiez** [comment]
websockets/ws#1358

**Comment by lpinca** [comment]
The subprotocol functionality is tested on ws, not sure what's wrong.

**Comment by vdiez** [comment]
Closing this now. As @lpinca pointed out in the websockets/ws#1358, using last autobahn release fixes the issue. Thanks to both.
