### ISSUE TITLE
Connection Lost after 30 seconds

### ISSUE THREAD

**Issue by msouzarunner** [crossbario/autobahn-js#349]
Hello everyone

     How do I proceed in case of a lost connection in order to automatically reconnect with the server.

**Comment by oberstet** [comment]
see "automatic reconnection" here: https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#connection-options

also, please note our mailing list for general questions (this is a bug tracker;):

https://groups.google.com/forum/#!forum/autobahnws
