### ISSUE TITLE
Supplying list of multiple transports doesn't fail-over as described

### ISSUE THREAD

**Issue by jamesremuscat** [crossbario/autobahn-js#352]
The [documentation](https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md) says that the `transports` option can be provided to `autobahn.Connection()` with 

> a list of transports to try successively

However, consider this simple example:

```javascript
const c = autobahn.Connection({
  transports: [
    {
      type: 'websocket',
      url: 'ws://not-a-real-wamp-router/'
    },
    {
      type: 'websocket',
      url: 'ws://an-actual-wamp-router/'
    }
  ],
  realm: 'realm',
  max_retries: 3
});

c.open();
```

Given the description above (and the example included in the docs), I would expect the following behaviour:

- Autobahn tries to connect to `ws://not-a-real-wamp-router/` and fails
- Autobahn retries a further three times to connect to `ws://not-a-real-wamp-router/` since `max_retries` is `3` (to save waiting around for the next step to happen!)
- Autobahn gives up on connecting to `ws://not-a-real-wamp-router/`, and moves on to the next transport in the list
- Autobahn connects to `ws://an-actual-wamp-router/` and succeeds.

However, what actually happens is:

- Autobahn tries to connect to `ws://not-a-real-wamp-router/` and fails
- Autobahn retries a further three times to connect to `ws://not-a-real-wamp-router/` since `max_retries` is `3` (to save waiting around for the next step to happen!)
- Autobahn gives up on connecting to `ws://not-a-real-wamp-router/`, and gives up all together. No further connection attempts are made.

Is the documentation in error, or is this a code bug?

Tested with Autobahn 18.3.2.

**Comment by markerikson** [comment]
Same as #191 .  The documentation appears to be wrong, since the code doesn't even try to do this.  It only falls back to other transport types if an error is thrown when creating the first transport, and I don't think errors _will_ be thrown the way the code is now.

**Comment by oberstet** [comment]
yeah, still missing (see #191 - closing this one as dup)
