### ISSUE TITLE
Chrome: onclose does not fire on reload or exit. 

### ISSUE THREAD

**Issue by johannwagner** [crossbario/autobahn-js#378]
Hey, 

I just encountered an issue, where Chrome does not execute the onclose callback, if the tab is reloaded or closed. Firefox does this correctly and fires this with the correct onclose reasons.

I think, this is a pretty classic race condition bug and may be owed the Chrome process/threads system, where the js executor is getting killed to early.

I tested this in Chrome 69.

What is the desired behaviour? I think, Firefox is doing fine.

Best Regards, 
    Johann

**Comment by oberstet** [comment]
This is not about ABJS, but specific browser implementations, hence OT (not an ABJS issue).

That being said, I would post that as a question on StackOverflow to get feedback/opinions.

The "desired behavior" would be specified by W3C (not sure which spec, but there will be one), and it is likely non trivial: eg what if some rogue JS is running in "onclose" handler? User will be sad. As a user, when I hit "close tab", I want it to close - now. But I'm pretty sure there are a lot more considerations.

Finally, you might also find sth useful here https://crossbario.com/blog/Websocket-Persistent-Connections/ - this specifically goes into the observed behavior of WebSocket connections in browsers when reloading etc
