### ISSUE TITLE
Why is randombytes needed?

### ISSUE THREAD

**Issue by champeric** [crossbario/autobahn-js#388]
With the latest version of AutobahnJS (18.10.1) installed from NPM, An error is thrown when doing `connection.open()`.
`could not create WAMP transport 'websocket':  { Error: Cannot find module 'randombytes'`

Commit 96724585440 added `var randomBytes = require('randombytes');` in _websocket.js_ so I suppose this module should be added to package.json.

**Comment by oberstet** [comment]
I'm wondering why it's needed at all;) I mean, this code only runs in Node, so why can't we just use `crypto.randomBytes`?

**Comment by oberstet** [comment]
`randombytes` is in the dependencies now: https://github.com/crossbario/autobahn-js/blob/master/package.json#L16
