### ISSUE TITLE
new s3 dependency has vulnerable dependencies

### ISSUE THREAD

**Issue by AviVahl** [crossbario/autobahn-js#390]
Noticed you've added `s3` to dependencies, as we got a security vulnerability warning in our repo (which uses autobahn):
https://github.com/wix/kissfs/pull/126

I'm not 100% certain, but it looks like `s3` isn't used in runtime. Could it be removed or moved to `devDependencies`?

**Comment by oberstet** [comment]
yeah, sorry, I should have reviewed more closely. @om26er pls do not add new dependencies without heads up. pls remove `md5` and `s3`. both are not needed

**Comment by om26er** [comment]
Sorry that got added by mistake this PR reverts it: https://github.com/crossbario/autobahn-js/pull/389

**Comment by AviVahl** [comment]
Thank you for the super quick response. Much appreciated. I'll be waiting for the new release and upgrade once it is out. :+1:

**Comment by oberstet** [comment]
Ok, this is fixed in v18.10.2:

* NodeJS: https://www.npmjs.com/package/autobahn/v/18.10.2
* Browser: https://www.npmjs.com/package/autobahn-browser/v/18.10.2 and https://github.com/crossbario/autobahn-js-browser/tree/v18.10.2
* Source: https://github.com/crossbario/autobahn-js/tree/v18.10.2
