### ISSUE TITLE
Throw causing improper exit

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/autobahn-js#397]
Calling close on process exit is causing exception sometimes `throw "connection already closed`  https://github.com/crossbario/autobahn-js/blob/master/lib/connection.js#L276

Throwing exceptions at the time of exit is causing the resources not be freed properly. It would be great if middleware, such as this package, do not throw and use return codes to indicate the status. 

In this case, asking to close an already closed connection is not so great an error that it should throw exception. Perhaps the method could simply ignore and return with some status "ALREADY_CLOSED" or similar. Or provide an `isClosed()` method so that caller can conditionally call the `close`

**Comment by oberstet** [comment]
works as designed

**Comment by KrishnaPG** [comment]
The so called _design_ **is** the problem, here. Middleware should not throw exceptions. 

If you believe out of all possible ways, throwing exception is the best way to design this, good luck.

For those others who visit this page later, and curious to learn how to design proper middleware, one of my old articles on MSDN blog [here](https://blogs.msdn.microsoft.com/gpalem/2008/02/28/well-designed-libraries/) illustrates how the masters do it. Check out how the Maya API did it, as an example, to learn why it became a world class product.

For the rest of the guys who believe work is done, when it starts to work, I have nothing to say.

I have been trying to promote WAMP as alternative to such as DeepStream etc. Looks like may be I am just mistaken.
