### ISSUE TITLE
tlsConfiguration option only gets applied when running in Node.js not in the browser

### ISSUE THREAD

**Issue by jenny-choe** [crossbario/autobahn-js#402]
I am trying to add TLS option to an app that involves 1) a browser running Autobahn|JS and 2) a remote server running Autobahn|Python. The tlsConfiguration seems to only be used websocket.js (line 126) if it's running in Node.js. Is it not possible to have a TLS connection on the browser?

Thanks,
Jenny

**Comment by oberstet** [comment]
When run in browsers, you can of course use TLS connections by using a secure WebSocket URL (`wss://`) - what you cannot do is modify the TLS settings being used. That is only possible in NodeJS (or in browser extensions). This isn't specific to AutobahnJS, but just how it works in general
