### ISSUE TITLE
Support NaCl SealedBox

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-js#405]
ABJS equivalent of https://github.com/crossbario/autobahn-java/issues/431

**Comment by oberstet** [comment]
So ABJS uses [TweetNaCl.js](https://tweetnacl.js.org/) (`"tweetnacl": ">= 0.14.3"`) which in itself, does not have sealed box, but there is [tweetnacl-sealed-box](https://github.com/whs/tweetnacl-sealed-box) which builds on the former adding sealed box, is MIT licensed, and is refered to [here](https://github.com/dchest/tweetnacl-js/blob/master/README.md#third-party-libraries-based-on-tweetnacljs).

> Neither TweetNaCl.js nor tweetnacl-sealed-box has undergone deep security evaluation (as far as I know), but the former is used "more widely" at least. The latter not (3 GH stars), but at least the guy who wrote it (https://github.com/whs) seems to be an active, real developer. Well, at one point we might have to look deeper or organize an effort to do so. For now, lets roll with it ..
