### ISSUE TITLE
Release v19.4.1

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#409]
**Run tests:**

In a first terminal:

```
make crossbar
```

In 2nd terminal:

```
make test
```

>> the test result files (test/*.txt) should be unmodified, which means all tests succeeded

**Build browser:**

```
make docker_build_toolchain
make distclean
make docker_build_browser
```

The generated files are here:

```
(cpy372_5) oberstet@intel-nuci7:~/scm/crossbario/autobahn-js$ ll build/
insgesamt 1120
drwxr-xr-x  2 root     root       4096 Apr 16 10:29 ./
drwxr-xr-x 10 oberstet oberstet   4096 Apr 16 10:29 ../
-rw-r--r--  1 root     root     762217 Apr 16 10:29 autobahn.js
-rw-r--r--  1 root     root      81249 Apr 16 10:29 autobahn.min.jgz
-rw-r--r--  1 root     root     273615 Apr 16 10:29 autobahn.min.js
-rw-r--r--  1 root     root        168 Apr 16 10:29 CHECKSUM.MD5
-rw-r--r--  1 root     root        195 Apr 16 10:29 CHECKSUM.SHA1
-rw-r--r--  1 root     root        273 Apr 16 10:29 CHECKSUM.SHA256
-rw-r--r--  1 root     root       1086 Nov 27 14:11 LICENSE
```

**Comment by oberstet** [comment]
@om26er it would be great if you could really takeover the _release process_ of ABJS. I justed did some smallish things and made sure the above technical build process works as of today ... but I really cannot continue doing that .. my available time will get even less, not more .. and also, the JS "ecosystem" (planet shit?) stresses me out particularily;) anyways, pls let me know what you would need, if I should explain anything, etc ..

**Comment by om26er** [comment]
@oberstet Ok, I am on it.

**Comment by om26er** [comment]
This is now done
