### ISSUE TITLE
XBR simple buyer

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#410]
ABJS should support XBR (in general), and provide the analogue of the Python XBR library simple XBR buyer for easy use in applications:

* https://github.com/xbr/xbr-protocol/blob/master/xbr/_buyer.py

**Comment by oberstet** [comment]
a prerequisite is the (low level) support for payload transparency: https://github.com/crossbario/autobahn-js/issues/297

**Comment by om26er** [comment]
This is done now, lets close ?
