### ISSUE TITLE
XBR simple seller

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#411]
ABJS should support XBR (in general), and provide the analogue of the Python XBR library simple XBR seller for easy use in applications:

* https://github.com/xbr/xbr-protocol/blob/master/xbr/_seller.py

**Comment by oberstet** [comment]
a prerequisite is the (low level) support for payload transparency: https://github.com/crossbario/autobahn-js/issues/297

**Comment by om26er** [comment]
This is done now, lets close ?

**Comment by oberstet** [comment]
yeah, the basic functionality is there I guess, so lets close
