### ISSUE TITLE
Issue with "invoke" rule names

### ISSUE THREAD

**Issue by jcgertig** [crossbario/autobahn-js#422]
The rule name for roundrobin was `roundrobing` it has just been updated an hour ago but i used the original and because there was no checking done and no useful error returned it went into a reconnection loop

**Comment by oberstet** [comment]
the change was certainly published only in a new release. but agreed: what we should have done to avoid wasting your time: properly maintain the https://github.com/crossbario/autobahn-js/blob/master/doc/changelog.md
