### ISSUE TITLE
How can I tweak the connection.transport.onmessage callback?

### ISSUE THREAD

**Issue by tonix-tuft** [crossbario/autobahn-js#429]
Hello,

using Autobahn.js, is there a way to access the contents of the raw messages sent by the server?

I would need this to inspect the raw JSON message sent by the server on the client side.

**Comment by oberstet** [comment]
you can enable debug mode like here https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#debug-mode

**Comment by tonix-tuft** [comment]
Thank you for your reply. Is there a way to access the onmessage raw data programmatically using JavaScript while not in debug mode?
