### ISSUE TITLE
Build XBR-less library packages

### ISSUE THREAD

**Issue by frol** [crossbario/autobahn-js#436]
Could you please shed some light on the "no dependencies" meaning in the README ("Features" section)?

Upgrade of Autobahn-js from 19.4.1 to 19.6.1 blew up my minified application bundle size from 490kb to 2.7MB (uncompressed, yet it is huge). I believe, It is related to #433.

**Comment by oberstet** [comment]
Uhh, yes, we probably should build a XBR-less version of AB for bundled use (and when XBR is unneeded)

**Comment by WyriHaximus** [comment]
FYI the `truffle-contract` in `package.json` still pulls on the entire (or at least of the) eth/web3 suite it seems.

P.S. Suddenly seeing eth related packages kind of freaked me out for a moment. Especially since there is no documentation mentioning eth or XBR mentioned anywhere in the readme.

**Comment by frol** [comment]
@WyriHaximus It freaked me out so much that I had even created an issue: https://github.com/crossbario/crossbar-examples/issues/127 :smile:

**Comment by oberstet** [comment]
@om26er what we could do is load the json abi files for xbr from the net when the user wants to do xbr stuff. on the other hand, _if_ the user wants to do xbr, then loading the json abi files from the net each time seems less cool. mmh ..

**Comment by om26er** [comment]
Once https://github.com/crossbario/autobahn-js/pull/453 lands, the size should come back to previous points. From there we will investigate to reduce size further, see https://github.com/crossbario/autobahn-js/issues/374
```
om26er@Intel-NUC-PC:~/scm/crossbario/autobahn-js/packages/autobahn/build$ ls -la
total 1156
drwxrwxr-x 2 om26er om26er   4096 Jul 18 05:22 .
drwxrwxr-x 5 om26er om26er   4096 Jul 18 05:22 ..
-rw-rw-r-- 1 om26er om26er 786648 Jul 18 05:22 autobahn.js
-rw-rw-r-- 1 om26er om26er  84118 Jul 18 05:22 autobahn.min.jgz
-rw-rw-r-- 1 om26er om26er 282312 Jul 18 05:22 autobahn.min.js
-rw-rw-r-- 1 om26er om26er    168 Jul 18 05:22 CHECKSUM.MD5
-rw-rw-r-- 1 om26er om26er    195 Jul 18 05:22 CHECKSUM.SHA1
-rw-rw-r-- 1 om26er om26er    273 Jul 18 05:22 CHECKSUM.SHA256
-rw-rw-r-- 1 om26er om26er   1086 Jul 18 04:58 LICENSE
```

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/453
