### ISSUE TITLE
Release 16.6.2

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#440]
we have 2 bug fixes to ship .. maybe it's worth doing a release? not sure, couple of issues are not yet resolved (after adding xbr) ..

**Comment by om26er** [comment]
@oberstet I think it makes sense to do a release. Especially because we fix some very explicit errors.

I can do the release if its a "yes" from your side.

**Comment by oberstet** [comment]
ok, cool! lets do a release ..
