### ISSUE TITLE
npm installed autobahn-js size is 120M

### ISSUE THREAD

**Issue by till-eugeneyu** [crossbario/autobahn-js#452]
having just autobahn-js v19.6.2 installed,
```
120M	./node_modules
```
it's much improved compared to v19.4.1 which was 281M.
but as we are developing IoT device with small data pool allowed, we can't afford this big library. is there anything I can do to reduce the module size?

**Comment by kuema** [comment]
I noticed the unusual size of the v19.4.1 version, too. There were some files present which don't belong in an NPM package, notably a complete Python virtual environment, a .cache and .npm directory, in sum about 250MB. I suspect it hasn't been properly cleaned before publishing.

The newer versions >=19.6 bring _a lot_ of dependencies due to this XBR stuff, which - in my opinion - should be moved into a separate plug-in package, if someone wants to use this stuff. See issues #449 and #436. 

These versions won't even build properly on my machine at work due to problems with native libraries (sha3 lib).

So for now we are sticking to 18.10.2 (~6MB, autobahn only) until there is a version _without_ XBR and all its dependencies again.

**Comment by till-eugeneyu** [comment]
@kuema Thanks, 6MB sounds a lot more reasonable.
We are at an awkward situation that we can't use v18 because v19 contains improvements in connection management, which fixes the issues we had in the previous versions.

**Comment by kuema** [comment]
We would like to use v19.x, too, but in its current state, size and dependency bloat it is just unusable.

I hope they find a proper solution to separate the XBR stuff from the core lib, because I believe most users just want a working (and slim) WAMP client library.

A quick solution for you could be a fork, removing the dependencies (as it was done in #449) and then installing the package directly via Github.

**Comment by oberstet** [comment]
> There were some files present which don't belong in an NPM package, notably a complete Python virtual environment, a .cache and .npm directory, in sum about 250MB. I suspect it hasn't been properly cleaned before publishing.

Heh? This is not the case at least with 19.7.2 which has a footprint ~120MB and there are no such files ^ in it:

* https://gist.github.com/oberstet/2b0a8630fab2b9c51069dd2e9ae33cb7

---

That being said, there is definitely room for improvement in general and I agree that there should be a way to install autobahn without the xbr bits. we'll work on reducing the size.

* https://gist.github.com/oberstet/dfd331609c73be9b6739389d941d4773
* https://gist.github.com/oberstet/3bc8a6281f0be27ad8d957ae00b349fc

@om26er there are different things do to IMO:

1. [ ] remove everything not marked "green" in the doc below in the "autobahn" sheet (remove tests, docs, etc)
2. [ ] move the xbr dependencies (see below) to `package.json|optionalDependencies` and advise users that have to preserve disk to install via `npm install --no-optional autobahn`
3. [ ] figure out how to handle `node_modules/autobahn/lib/xbr/contracts/*.json`: these files are 5MB (not the biggest fish to fry .. but only needed for xbr)

---

of the current deps:

```
  "dependencies": {
    "cbor": ">= 3.0.0",
    "crypto-js": ">=3.1.8",
    "eth-sig-util": ">=2.2.0",
    "msgpack5": ">= 3.6.0",
    "sha3": ">=2.0.1",
    "truffle-contract": ">=4.0.10",
    "tweetnacl": ">=0.14.3",
    "tweetnacl-sealedbox-js": ">=1.1.0",
    "uuid": ">=3.3.2",
    "web3": ">=1.0.0-beta.53",
    "web3-utils": ">=1.0.0",
    "when": ">= 3.7.7",
    "ws": ">= 1.1.4"
  },
```

(at least) these should be moved to optional:

* eth-sig-util
* truffle-contract
* web3
* web3-utils

**Comment by oberstet** [comment]
```
find node_modules/* -maxdepth 0 -type d -exec du -bs {} \;
find node_modules/autobahn/ -type f -exec du -bs {} \;
```

[ab-sizes.pdf](https://github.com/crossbario/autobahn-js/files/3400494/ab-sizes.pdf)

**Comment by oberstet** [comment]
rgd `optionalDependencies`: is there a way to have multiple installation flavors with npm?

Eg python pip supports that, eg users can do

* `pip install autobahn` => install the very minimal 
* `pip install autobahn[twisted, xbr]` => install twisted networking framework and all xbr stuff
* ...
* `pip install autobahn[all]` => install everything

so ABPy has a whole bunch of flavors: https://github.com/crossbario/autobahn-python/blob/master/setup.py#L238

is there sth similar in the JS world?

**Comment by kuema** [comment]
> Heh? This is not the case at least with 19.7.2 which has a footprint ~120MB and there are no such files ^ in it:

This was only the fact in v19.4.1 specifically, because the `venv`, `.cache` and `.npm` directories were present in the published NPM package.

**Comment by kuema** [comment]
Regarding the dependencies:
I think optional deps are only a short-term solution. You cannot specify this in the package.json of the user project, so you have to install with `--no-optional` for all your packages you're depending on.

I haven't seen something like installation flavors with NPM. However, there are NPM [peerDependencies](https://nodejs.org/es/blog/npm/peer-dependencies/) which can be helpful with plugin-like packages. This prevents issues with different versions being installed by using the version of the "host" package. We just ran into this problem at work last week.

The Winston logger is doing something similar to extend the logger lib with additional transports, formats, etc. via separate packages.

https://github.com/winstonjs/winston
https://github.com/winstonjs/winston-daily-rotate-file

So you would have 2 packages, say `autobahn` and  `autobahn-xbr`, with `autobahn-xbr` declaring  `autobahn` as peer dependency. `autobahn-xbr` would then use the correct `autobahn` module and could register itself that one.

I believe that would be the better solution in long-term.

**Comment by oberstet** [comment]
> This was only the fact in v19.4.1 specifically

Ok, yes

> You cannot specify this in the package.json of the user project, so you have to install with --no-optional for all your packages you're depending on.

Agreed, this would be bad. 

> So you would have 2 packages, say autobahn and autobahn-xbr, with autobahn-xbr declaring autobahn as peer dependency. 

If what you describe is really the state of the art of doing flavors in the JS world, then I agree that we probably have to use 2 packages. which I would have preferred to avoid .. but

Before we go down that route, IMO it would be good to get some further confirmation / consensus on ^ (not suggesting you are wrong or anything .. just want to draw on more opinions/know-how if possible). I would want to nail it now and once for all, and not again change everything later on. @om26er opinions?

**Comment by kuema** [comment]
That is reasonable, of course.

I wouldn't compare it to installation flavors that pip provides nor call it state of the art. At the end it just comes down to dependency management between a "host" and "plug-in" packages, and those peerDependencies are really helpful in regard to that.

I am aware that it would require some work to get this sort of modularization done, but I think it is worth it. Especially with all these dependencies the XBR feature draws in.

As a bonus for making `autobahn` extensible, future features like XBR could easily be provided as a separate package without touching the core. :smiley:

**Comment by om26er** [comment]
> Before we go down that route, IMO it would be good to get some further confirmation / consensus on ^ (not suggesting you are wrong or anything .. just want to draw on more opinions/know-how if possible). I would want to nail it now and once for all, and not again change everything later on. @om26er opinions?

So I looked into this a bit and found that https://github.com/ethereum/web3.js handles a similar situation cleanly. They put every package into a `packages` directory where they have their own `package.json` file. The root of the source tree also has a `package.json` which is only for the ethereum core.

If we replicate a similar model we will have
root ==> packages ==> autobahn/lib/
root ==> packages ==> autobahn-xbr/lib/

Then the autobahn-xbr library could also add a `PeerDependencies` entry for autobahn but more importantly I want to mention that the xbr library has no direct dependency on autobahn, the library only expects a `Session` instance created by a user's app.

**Comment by kuema** [comment]
That is similar to how we handle our package repos at work.

I have used some ideas from these sources:
https://github.com/boennemann/alle
https://knolleary.net/2019/03/21/moving-node-red-to-a-monorepo/

The only difference is, that they create a `node_modules` dir in `packages` to make use of NodeJS' module loading order. This way it is easier to develop multiple depending packages in one workspace without the need to `npm link` anything. They also use a package.json at the root of the repo, so you only have to install the dependencies at this level, and not per package.

All in all, I am pretty satisfied with the solution Node-RED is using now, which works quite well in our use case. Maybe that approach will work for Autobahn as well.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/453
