### ISSUE TITLE
authextra on change

### ISSUE THREAD

**Issue by robintema** [crossbario/autobahn-js#458]
Hi, 
I was wondering if there is a way to "update" the authextra value without creating a new connection.
I want to store some extra information on the authextra param that might be changed during a session. If I have to update authextra that means I have to close the existing connection and create a new one or is there a way to reload the connection?

```
return new autobahn.Connection({
				url: WSURL,
				realm: "realm1",
				authextra: {'extra': USER RELATED DATA}
			});
```

**Comment by oberstet** [comment]
nope, that's not possible: authextra is not a general facility for keeping per-session state on the router .. authextra is exclusively used initially for authenticating the wamp session.
