### ISSUE TITLE
XBR: docker image build fails

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#470]
ok, I've added `autobahn-xbr` to the Docker builds (https://github.com/crossbario/autobahn-js/commit/cc3950c7b548a69d0214af44dddea22ff80d4da1), but it fails: https://gist.github.com/oberstet/7aa0512c36445660a49cab14c064ad8b

**Comment by om26er** [comment]
fixed via https://github.com/crossbario/autobahn-js/pull/480
