### ISSUE TITLE
Handle not_authorized error

### ISSUE THREAD

**Issue by charisra** [crossbario/autobahn-js#482]
Hi to all, 

I have a web app that's using Crossbar.io and Autobahn, React on the frontend and Python on the backend. 
I'm using a session_authorizer function (dynamic authorization) to determine if the caller has authorization to call some RPCs:
`async def session_authorizer(dbcon, dbapi, logger, session, uri, action, options):`

When a user's session expires, I need a way for the frontend to become aware. 
The backend currently **correctly denies access** to the RPC call, but I want to take some action on the frontend, too and I can't find a way to do so. 

That's because the session_authorizer function communicates only with Crossbar and provides no way to notify the frontend that the user is no longer authorized. 

I'm getting this error on my browser console:
`Potentially unhandled rejection [5] {"error":"wamp.error.not_authorized","args":["session is not authorized to call procedure 'com.panel.func'"],"kwargs":{}} (WARNING: non-Error used)`

Is there something I'm missing? A way for the connection to error out when authorization is lost or some other way?

Thanks

**Comment by meejah** [comment]
There are likely many ways to accomplish what you desire .. can you say more about what exactly you want? (e.g. if you're expiring authorization somehow in the backend, it could use `publish()` to push a notification to the frontend or the frontend could have a method registered that's called .. or even just respond to the `wamp.error.not_authorized` by doing whatever it needs to do to re-enable authorization)

**Comment by meejah** [comment]
p.s. this isn't really a bug and questions are better asked in the forum: https://forum.crossbar.io/
