### ISSUE TITLE
possible assert issue when running under different nodejs vm contexts

### ISSUE THREAD

**Issue by lajosbencz** [crossbario/autobahn-js#488]
The line at
https://github.com/crossbario/autobahn-js/blob/d0d34813110f64127b2b76ecfa7eba7adda5a430/packages/autobahn/lib/session.js#L1217
fails for me on NodeJS 11 and 12, even though the kwargs parameter is an object.

I gave up debugging when seeing these watch values:

![image](https://user-images.githubusercontent.com/8420835/73989969-fcbd6e00-4947-11ea-8255-1067d7510ce0.png)

It's not necessarily an autobahn related issue, but if I change those (and all related) checks to ```kwargs typeof === 'object'```, everything works fine.

I've seen you already had trouble with the array checks a while back, is there any chance to use typeof for the object checks aswell? I could create a PR for it!

**Comment by oberstet** [comment]
The code is fine (your problem must be coming from somewhere else) it seems - here is a quick test on Node 10 and 12:

```console
oberstet@intel-nuci7:~$ /home/oberstet/node-v10.16.0-linux-x64/bin/node --version
v10.16.0
oberstet@intel-nuci7:~$ /home/oberstet/node-v10.16.0-linux-x64/bin/node 
> ({} instanceof Object);
true
> 
```

```console
oberstet@intel-nuci7:~$ /home/oberstet/node-v12.15.0-linux-x64/bin/node --version
v12.15.0
oberstet@intel-nuci7:~$ /home/oberstet/node-v12.15.0-linux-x64/bin/node
Welcome to Node.js v12.15.0.
Type ".help" for more information.
> ({} instanceof Object);
true
> 
```

**Comment by kuema** [comment]
The problem isn't that far-fetched. I you use [Node-JS' VM](https://nodejs.org/dist/latest-v10.x/docs/api/vm.html) module to execute user code, the objects created in there are different prototype instances. So every `instanceof` check outside will fail.
For example, this happens when using [Node-RED](https://nodered.org/) and create objects within a function node and pass these to Autobahn outside of the VM.

So replacing the "hard" instance check with `typeof === 'object'` would be welcome.

**Comment by oberstet** [comment]
> that works with the VM case

ok, if there is an issue for such a specific case, lets see if there is sth we can do that definitely solves that, while at the same time doesn't introduce regressions in other environemtns where autobahn runs.

so we first would need a unit test for running autobahn within different nodejs vm contexts and adding that to the travis ci in this repo. or maybe run all our existing tests from within different VM contexts ..

also, probably independent of that, I have used autobahn from node-red .. quite some time ago. not sure when the assert came into autobahn.

there even seems to be a library these days https://github.com/moliqingwa/node-red-contrib-wamp ..

**Comment by oberstet** [comment]
rgd "regression safety", seems we could simply add an "isinstanceof || typeof" and be on the safe side (if we'd had an automated unit test that failed in the first place):

```
(cpy381_1) oberstet@intel-nuci7:~$ /home/oberstet/node-v10.16.0-linux-x64/bin/node
> typeof {} === 'object'
true
> ({} instanceof Object);
true
> 
(To exit, press ^C again or type .exit)
> 
(cpy381_1) oberstet@intel-nuci7:~$ /home/oberstet/node-v12.15.0-linux-x64/bin/node
Welcome to Node.js v12.15.0.
Type ".help" for more information.
> typeof {} === 'object'
true
> ({} instanceof Object);
true
> 
(To exit, press ^C again or ^D or type .exit)
> 
```

**Comment by kuema** [comment]
That sounds reasonable.

Up to now we have worked around the "instanceof" problem by creating the object outside the VM. But a clean solution to this would be really appreciated.

> there even seems to be a library these days https://github.com/moliqingwa/node-red-contrib-wamp 

We don't use that particular contrib node. It didn't exist back then, so we developed our own with some more advanced features.

BTW: We have been using WAMP in conjunction with Node-RED for many years now. Quite the couple these two technologies. 😄

**Comment by lajosbencz** [comment]
That's the thing - I'm not using any "exotic" runtime, it's vanila NodeJS 12 LTS.

I wrote an AutobahnJS wrapper [plugin package for vue](https://github.com/lajosbencz/vue-wamp), which works fine, we have been using the 2.x version in production successfuly.

The next step in the Vue ecosystem is Nuxt, which facilitates server-side rendering and other goodies.
I created another package, [nuxt-wamp](https://github.com/lajosbencz/nuxt-wamp), which in turn wraps around vue-wamp and handles the server-side part.

This is where it gets interesting:

At first I duplicated the code instead of requiring vue-wamp through npm, and that worked fine. Server-side was rendering as expected, awesome!

Then I refactored vue-wamp a bit to be less of a spaghetti code, and required that from nuxt-wamp.
This was the step when it broke down, and that watch sceenshot was made.

I tried to produce an isolated example in a single file, but cannot... so here is a "stack-trace" through the different components:

https://github.com/lajosbencz/nuxt-wamp/blob/73314907e2fb3fe2e3879fc2ca9a01c53da848dc/src/plugin.js#L2

https://github.com/lajosbencz/nuxt-wamp/blob/73314907e2fb3fe2e3879fc2ca9a01c53da848dc/src/plugin.js#L27

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/index.js#L8

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/index.js#L48

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/Context.js#L30

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/Context.js#L154

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/Connection.js#L167

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/Connection.js#L12

https://github.com/lajosbencz/vue-wamp/blob/745b0de7dbc5961673567da6589ce48112e2f4e7/src/Connection.js#L17

https://github.com/crossbario/autobahn-js/blob/d0d34813110f64127b2b76ecfa7eba7adda5a430/packages/autobahn/lib/session.js#L1213

I am baffled as to how to even begin to solve this (without modifing autobahn's assertions).... any help would be appreciated!

**Comment by oberstet** [comment]
@lajosbencz we can surely change the assert in autobahn - together with a CI test covering the case (different nodejs vm contexts). when someone steps up with a PR (my work queue is full;)

**Comment by lajosbencz** [comment]
I managed to reproduce the issue:

```js
var context = {kwargs: {foo: 'bar'}, isObj: false};
vm.createContext(context);
var code = 'kwargs.baz = \'bax\'; isObj = kwargs instanceof Object';
vm.runInContext(code, context);
console.log(context.isObj);
```

results in:

```bash
# false
```

I haven't read any contribution guide, I hope all is well i the PR...

**Comment by oberstet** [comment]
> I haven't read any contribution guide, I hope all is well in the PR...

yeah, PR looked good, so merged! the issue should hence be fixed (on master)

also, no, we don't have a contribution guide (we should .. but in any case, you basically blended in code style etc into what's there already, so cool)

**Comment by oberstet** [comment]
here is output from the new CI test on master for this https://travis-ci.org/crossbario/autobahn-js/builds/647461691#L312 .. all green, perfect

**Comment by lajosbencz** [comment]
Awesome, thanks!
When is a new release to be expected?:]

**Comment by oberstet** [comment]
^ since it's on master now, it'll be in the next release (v20.2.2 likely)
