### ISSUE TITLE
Is it guaranteed that after connection.onclose callback session.isOpen of the closed connection becomes false right-away?

### ISSUE THREAD

**Issue by tonix-tuft** [crossbario/autobahn-js#506]
Hello,

I couldn't find this information in the API docs.
`autobahn.Session` has an `isOpen` property which, if a connection is closed, is set to `false`.

I noticed that if a connection is suddenly closed for some reason (network error, forcedly closed by the WebSocket server, etc...), in the `connection.onclose`, `session.isOpen` still has a value of `true`:

```js
var currentSession;
connection.onopen = function (session, details) {
    currentSession = session;
}

connection.onclose = function (reason, details) {
    // Outputs: true and a reference to the session, which if expanded shows `false` for `isOpen`.
    console.log("onclose", currentSession.isOpen, currentSession);
}
```

![Screen Shot 2020-04-30 at 18 09 07](https://user-images.githubusercontent.com/10134421/80733284-c68a2780-8b0d-11ea-89b9-66e454d6e19c.png)

![Screen Shot 2020-04-30 at 18 09 21](https://user-images.githubusercontent.com/10134421/80733286-c9851800-8b0d-11ea-8e51-6fa146209b28.png)

When does `autobahn` set `session.isOpen = false` on the previous `autobahn.Session`? Is it guaranteed that right after `connection.onclose = function (reason, details) {...}` executes, the corresponding's session `session.isOpen` flag is set to false right-away?

Or does `autobahn` set `session.isOpen = false` on the previous session only when a new session is available in `connection.onopen`?

Thank you for your attention.

**Comment by om26er** [comment]
Please use our forum to ask questions https://forum.crossbar.io/. We use GitHub issues for tracking bug reports and feature requests only.

**Comment by tonix-tuft** [comment]
OK, thank you!
