### ISSUE TITLE
Unsubscribing on closed session does not remove Subscriptions

### ISSUE THREAD

**Issue by svanderweyst-cpr** [crossbario/autobahn-js#508]
When attempting to unsubscribe from topics after a connection has closed, the references to the subscriptions are not removed, potentially leading to memory leaks.

In our situation, our subscription handlers happened to have implicit references to the session.
I believe that if session.unsubscribe is called, that the end result should be that the list of subscriptions in the session should no longer contain that subscription.

Since there were still references to the session in the subscriptions, the session was never being GC'd

**Comment by oberstet** [comment]
@svanderweyst-cpr should be fixed via your PR https://github.com/crossbario/autobahn-js/pull/509, right?

**Comment by svanderweyst-cpr** [comment]
Yes; this should be fixed now. Thanks for the quick response.
