### ISSUE TITLE
doc/getting-started.md - correction for link to other wamp 2 compatible routers

### ISSUE THREAD

**Issue by TraceOrdin** [crossbario/autobahn-js#510]
Hi! Thanks for your hard work on this project. 

Noticed a small broken link issue in two locations on the page at:
On the https://github.com/crossbario/autobahn-js/blob/master/doc/getting-started.md

Here's a working link: https://wamp-proto.org/implementations.html

They currently go to http://wamp.ws/implementations/ which is showing an xml error.

Locations:
- near the top under the 'WAMP Router' heading, the link is the text 'list of WAMP v2 compatible routers'
- near the bottom under the 'Running a WAMP router' heading, the link is the text 'WAMP router implementations exist'

**Comment by oberstet** [comment]
ah, yes. thanks for reporting this doc bug!
