### ISSUE TITLE
Compilation fails under yarn 2 environment

### ISSUE THREAD

**Issue by xaroth8088** [crossbario/autobahn-js#514]
My environment: `yarn 2` + `webpack 4` + `pnp-webpack-plugin`

When I use Autobahn version 20.2.2, my project builds and runs cleanly.  However, when I update to 20.4.1, my builds fail and I get the following error message:

```ERROR in ../.yarn/cache/autobahn-npm-20.4.1-a7d782c080-fb4da31ae2.zip/node_modules/autobahn/lib/util.js
Module not found: Error: autobahn tried to access fs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: fs (via "fs")
Required by: autobahn@npm:20.4.1 (via /react-client/.yarn/cache/autobahn-npm-20.4.1-a7d782c080-fb4da31ae2.zip/node_modules/autobahn/lib/util.js)
```

This appears to be triggered by [this change](https://github.com/crossbario/autobahn-js/compare/v20.2.2...v20.4.1#diff-75124a7bab3c79cccab0f4fdf1c8a6e0R421).

Workaround for now is to just keep running v20.2.2.

**Comment by xaroth8088** [comment]
v20.6.1 is also affected by this issue.

**Comment by scasei** [comment]
Same problem here, v20.7.2

**Comment by oberstet** [comment]
as far as I know, `fs` is a builtin module that doesn't require a require. if so, pls report this to yarn.
