### ISSUE TITLE
Multiple topics

### ISSUE THREAD

**Issue by alexolliveira** [crossbario/autobahn-js#549]
How do I subscribe to two or more topics on autobahn.js?
I'm trying:
conn.subscribe('topic1','topic2', function(topic, data){}
but it isn't working.
Anybody help me, please.
Thanks!

**Comment by oberstet** [comment]
You can find an example how to subscribe on multiple topics (or patterns) here: https://github.com/crossbario/autobahn-js/blob/master/packages/autobahn/test/test_pubsub_multiple_matching_subs.js (the folder has more examples doing similar).

Eg one useful pattern is in above example:

```javascript
var dl2 = [];

dl2.push(session_b.subscribe('com..topic1', on_event, {match: 'wildcard'}));
dl2.push(session_c.subscribe('com.myapp', on_event, {match: 'prefix'}));
dl2.push(session_d.subscribe('com', on_event, {match: 'prefix'}));
dl2.push(session_e.subscribe('com.myapp.topic1', on_event, {match: 'exact'}));

autobahn.when.all(dl2).then(
function (subs) {
    console.log('all test sessions subscribed!');
    ...
```

**Comment by alexolliveira** [comment]
Thank you for helping, buddy!
