### ISSUE TITLE
Release 22.10.1

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-js#562]

**Comment by om26er** [comment]
@oberstet I have released 22.10.1 on npmjs but cannot push to https://github.com/crossbario/autobahn-js-browser, can you please give me permissions to that repository

**Comment by oberstet** [comment]
ok, I've given you "Write" on both "crossbario/autobahn-js" and "crossbario/autobahn-js-browser"

**Comment by om26er** [comment]
done
