### ISSUE TITLE
autobahn js => es6 ?

### ISSUE THREAD

**Issue by antonymott** [crossbario/autobahn-js#564]
Is there an es6 transpilation of autobahn.js? I googled but couldn't find autobahn.mjs or links to an es6 version. I'm trying out autobahn with Deno which doesn't work easily with node code unless it's es6.

**Comment by oberstet** [comment]
mmh, not sure but not that I'm aware of.

are we talking about https://deno.land/ btw? what's that and why do they insist on outdated tech?

**Comment by antonymott** [comment]
Yeah, I dug into the code a bit more and fixed the 4 problems locally. If there aren't many use cases like this, perhaps there's nothing more to be done at this time, and perhaps we just close this issue? For anyone in the future wanting a quick fix for the same issue, I made the deno.land complaints go away by editing (locally) the npm package autobahn-browser: first I switched to the un-minified version (which you or some thoughtful maintainer helpfully included in the package!). Once I switched to autobahn.js as default, it was easy to fix 3 of the 4 issues, the code "!x in y" is parsed as "(!x) in y" by adding parentheses to get "!(x in y)". Finally, I changed line 1614 j = eval('(' + text + ')'); as direct eval with a bundler was not recommended. Deno minifies and bundles js so no production performance is affected by using the edited un-minified version in the npm package. Hope this helps someone!

**Comment by oberstet** [comment]
> For anyone in the future wanting a quick fix for the same issue,

thanks for leaving your notes!

> I am closing this issue nevertheless since es6 has probably exotic demand, and proper support for an es6 build flavor would be more effort
