### ISSUE TITLE
MsgPack serialization

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#67]
https://www.npmjs.org/package/msgpack-js-v5
https://github.com/creationix/msgpack-js

**Comment by distopik** [comment]
+1 would be very happy to see

**Comment by athibaud** [comment]
+1 any update on this?

**Comment by arantir** [comment]
+1

**Comment by kolis** [comment]
+1

**Comment by EnGassa** [comment]
Is there a plan to merge this request?
Is there any additional work required that we can help with?

**Comment by oberstet** [comment]
@EnGassa I'd be happy to merge a PR!

**Comment by goeddea** [comment]
There was https://github.com/crossbario/autobahn-js/pull/90, which contained code for, among other things, msgpack, but was abandoned.

**Comment by oberstet** [comment]
This PR was for Longpoll, not msgpack. Longpoll is implemented in AutobahnJS now.

**Comment by goeddea** [comment]
My bad - I'd had a look at https://github.com/arnoschn/AutobahnJS/commit/c8cf5d73ff39aec33738ec9bbac460647a9416b1 which does contain a couple of files regarding messagepack - and assumed this was part of the PR.

**Comment by oberstet** [comment]
But yeah, msgpack would be a nice addition. The main thing to make it work is: internal code refactoring to properly abstract serialization. If we have that, adding msgpack should be next to trivial. Also: CBOR rocks! It's both faster and smaller than msgpack. In fact, AutobahnPython and Crossbar.io prioritize serializers as follows: first cbor, then msgpack, then json. JSON is the fallback that should work anyway, but AB/CB talk CBOR nowerdays.

**Comment by oberstet** [comment]
@goeddea ah, there is a piece of info in there we should remember:

+// taken from: https://github.com/creationix/msgpack-js-browser
+// fixes implemented from: https://github.com/chakrit/msgpack-js/blob/128e53d78d456c94d80cfb7d8143b5eb1d29e650/msgpack.js

**Comment by agronholm** [comment]
I implemented msgpack support for autobahn-js but had trouble running the tests. I asked for help on the Google group but never received a reply so I abandoned the effort.

**Comment by oberstet** [comment]
@agronholm sorry! I missed your post on the mailing list. do you have a link to the post? I can't fine it ..

**Comment by agronholm** [comment]
I can't find it either :/
I'll check my work again and see what I was missing. I recall it was a problem with Crossbar so there's a chance it has already been resolved.

**Comment by agronholm** [comment]
Ah, now I remember. It seems that the tests require a WAMP router to be running on ws://127.0.0.1:8100/ but the README says nothing about the expected configuration of that router.

**Comment by oberstet** [comment]
@agronholm please see https://github.com/crossbario/autobahn-js/blob/master/package/test/README.md .. I added some text  -- it needs a router or `ws://localhost:8080/ws` (https://github.com/crossbario/autobahn-js/blob/master/package/test/testutil.js#L33)

**Comment by mfojtak** [comment]
+1 for this feature. Cannot consume binary data in browser which is a pain. The issue is almost two years old. Hope it's not dying.

**Comment by agronholm** [comment]
I'll try to work on it some more on the weekend.

**Comment by agronholm** [comment]
I just tried to run the test suite, but nothing happens. I have a crossbar instance (0.10.2) running with default settings. "npm test" started the test suite but it hangs after printing "test.js" to the console.

**Comment by goeddea** [comment]
Just tried with the current Crossbar.io release (0.12.1) and the tests run (though a few fail since we haven't updated the tests to reflect the current amount of details passed to a callee).

**Comment by agronholm** [comment]
Upgrading my Crossbar seems to have worked. One test is failing. It's too bad the autobahn-js docs don't say what version of Crossbar I'm supposed to test against.
```
> nodeunit test/test.js


test.js
✔ testConnect
✔ testRpcArguments
✔ testRpcComplex
✔ testRpcError
✖ testRpcOptions

Assertion Message: 
Expected:

0 "Connected"
1 "All registered."
2 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
3 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
4 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
5 "Squared" 4
6 "Squared" 0
7 "Squared" 4
8 "All finished."



Got:

0 "Connected"
1 "All registered."
2 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
3 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
4 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
5 "Squared" 4
6 "Squared" 0
7 "Squared" 4
8 "All finished."



AssertionError: 
Expected:

0 "Connected"
1 "All registered."
2 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
3 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
4 "Someone is calling me;)" {"caller":0,"procedure":undefined,"progress":null}
5 "Squared" 4
6 "Squared" 0
7 "Squared" 4
8 "All finished."



Got:

0 "Connected"
1 "All registered."
2 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
3 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
4 "Someone is calling me;)" {"caller":0,"caller_authid":undefined,"caller_authrole":undefined,"procedure":"com.myapp.square","progress":null}
5 "Squared" 4
6 "Squared" 0
7 "Squared" 4
8 "All finished."



    at Object.ok (/home/alex/checkout/AutobahnJS/package/node_modules/nodeunit/lib/types.js:83:39)
    at /home/alex/checkout/AutobahnJS/package/test/test_rpc_options.js:93:25
    at tryCatchReject (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/alex/checkout/AutobahnJS/package/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:415:13)

✔ testRpcProgress
✔ testRpcSlowsquare
✔ testRpcRouting
✔ testRpcCallerDiscloseMe
✔ testPubsubBasic
✔ testPubsubComplex
✔ testPubsubOptions
✔ testPubsubExcludeMe
✔ testPubsubExclude
✔ testPubsubPrefixSub
✔ testPubsubWildcardSub
✔ testPubsubPublisherDiscloseMe
```

**Comment by agronholm** [comment]
Using master versions of autobahn and crossbar I get 5 failures instead of 1. @goeddea did you get the test suite to run without errors? If so, how?

**Comment by agronholm** [comment]
I think that one test was broken by changeset 08ba2a791edcb4e13fe3985ef66c34232f50829b. Anyways, other than that I have a working setup and should be able to finish the patch now.

**Comment by agronholm** [comment]
Done: https://github.com/crossbario/autobahn-js/pull/187

**Comment by agronholm** [comment]
This can be closed now?

**Comment by mfojtak** [comment]
This doesn't seem to work for me. I tried this:

```
connection = new autobahn.Connection({
		 transports: [{
			'type': 'websocket',
			'url': 'ws://40.205.196.29:8080',
			'protocols': ['wamp.2.msgpack']
		}], realm: 'realm1', authmethods: ["wampcra"], onchallenge: onchallenge});
```

It throws: Uncaught TypeError: Cannot read property 'serialize' of undefined. TypeError: k.serializer is undefined

When I change it to 'wamp.2.json' then it works.

**Comment by agronholm** [comment]
What version of autobahn-js are you using? I don't think wampcra works with the latest one, which made me wonder.

**Comment by mfojtak** [comment]
I am using this verison https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz
My router supports msgpack and works with C++ client.
Wampcra works fine.
It is just js not working with msgpack. Which sucks because I am transporting realtime video signal using wamp and cannot use json. Am I doing something wrong? Has anybady ever made js working with msgpack?
