### ISSUE TITLE
Implement WAMP long-poll transport

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#70]

**Comment by deceze** [comment]
Should the http://autobahn.ws front page still say "___upcoming___: long-poll fallback (old browsers)"? Is there documentation available/necessary for this feature?

**Comment by oberstet** [comment]
@deceze ah, thanks! WAMP-over-Long-poll is of course shipped!

The only docs and example code right now is here:
* http://crossbar.io/docs/WAMP-Long-Poll-Service/
* https://github.com/crossbario/crossbarexamples/blob/master/longpoll/web/index.html#L16


@goeddea: could you fix the Autobahn main landing page?

"upcoming: long-poll fallback (old browsers)"

=>

"works in older browsers (via HTTP-Long-poll transport)

**Comment by goeddea** [comment]
@oberstet - fixed the autobahn landing page
