### ISSUE TITLE
support pluggable protocols / encoders

### ISSUE THREAD

**Issue by arnoschn** [crossbario/autobahn-js#87]
Analogue to autobahn.transports.register() it would be great to be able to register new encoders / protocols with autobahn.

With a pluggable architecture, protocol changes will be a lot easier to handle.

```javascript
autobahn.protocols.register("wamp.1", Wamp1Protocol);
autobahn.encoders.register("msgpack", MsgpackEncoder);
```

**Comment by oberstet** [comment]
AutobahnJS now has pluggable transports and serializers:

* https://github.com/crossbario/autobahn-js/tree/master/package/lib/transport
* https://github.com/crossbario/autobahn-js/blob/master/package/lib/serializer.js

**Comment by bramus** [comment]
If you're getting a "Cannot read property 'serialize' of undefined" error in `transport/websocket.js`, here's a workaround: 

https://github.com/crossbario/autobahn-js/issues/231#issuecomment-762838867
