### ISSUE TITLE
Implement authentication: one-time token

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#88]
See: https://github.com/tavendo/WAMP/issues/70

**Comment by oberstet** [comment]
WAMP-Ticket authentication is implemented: https://github.com/crossbario/crossbarexamples/tree/master/authentication/ticket/static

**Comment by beerteam** [comment]
Hello, where is information about authorization in documentation in autobahn js

**Comment by goeddea** [comment]
@beerteam - This is an issue tracker, not a support forum (https://groups.google.com/forum/#!forum/autobahnws)

Authorization is covered in the Crossbar.io documentation - http://crossbar.io/docs/Authorization/
