### ISSUE TITLE
Automatic reestablishment of prefixes and subscriptions upon reconnect

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#9]
The lifetime of topic subscription with AutobahnJS starts with subscribe() and ends with unsubscribe() or at latest with the end of the session.

An application may want to resubscribe all topics upon a reconnect of session automatically.

API-wise, the only thing needed would be an option to activate this behavior.

Internally, the subscription table with all event handler should be saved when the session is lost, and all subscription reactivated upon reconnect.

**Comment by activeperception** [comment]
Hi, 

I'm finding this to be an issue in my application and can't think of any other way to go about it. 

In a decently sized application you would expect the registration / subscriptions to be 'distributed' across multiple classes/components/controllers therefore not all re-registration can happen in the onopen method. 

For our app we're storing the registrations/subscriptions in a AngularJS factory that also abstracts all controllers from Autobahn details. On reconnect we iterate through the stored registrations/subscriptions and re-register...this is something that can probably be done in an easier and cleaner way internally by autobahn using session.subscriptions and session.registrations. What do you think?

/Raffaele

**Comment by oberstet** [comment]
The session is destroyed when the connection is lost. Upon (automatic) reconnection, a _new_ session object is created. I don't think scattering subscribe/register over classes is a good approach. But then, I don't know much about AngularJS. So I would need to have to look at a (larger) Angular/WAMP application to get a "feeling" for where the issues are. We have done large apps using AutobahnJS and Knockout, and there, we didn't have issues.
