### ISSUE TITLE
add 'disclose_me' per-connection option

### ISSUE THREAD

**Issue by goeddea** [crossbario/autobahn-js#94]
In most of the WAMP applications I've worked on so far, the caller does not receive the publish generated by the backend to update other clients.

To enable this, I need to add the option "disclose_me: true" to each call so that the backend receives the session id of the caller and can then do "exclude: [caller]".

Ideally, I'd be able to change the default value for disclose_me for the session.

This would probably be easiest through setting a property on the session object.

**Comment by oberstet** [comment]
Caller/publisher disclosure is now strictly controlled by the router (configuration) only
