### ISSUE TITLE
Add Autobahn|JS to CDN(s)

### ISSUE THREAD

**Issue by goeddea** [crossbario/autobahn-js#99]
possible CDNs are:
- http://cdnjs.com/
- http://www.jsdelivr.com/

**Comment by KrishnaPG** [comment]
wondering if this is complete. +1 otherwise. Especially `jsdelivr` has this nice feature that lets us pick multiple js files with [single request](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request)

**Comment by AndreMiras** [comment]
Until then we can use:
http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.js
Or version specific:
https://autobahn.s3.amazonaws.com/autobahnjs/0.10.0/autobahn.min.js

More details in:
https://github.com/crossbario/autobahn-js/wiki/Releasing

**Comment by Jichao** [comment]
@goeddea There is an issue https://github.com/cdnjs/cdnjs/issues/7102#issuecomment-261843738 in cdnjs, You could contact with the them.

**Comment by oberstet** [comment]
won't fix
